<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CustomersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('customers')->insert([
            [
                'id' => 1,
                'party_type' => 'Customer',
                'cid' => 'Titan',
                'cust_name' => 'TITAN COMPANY LIMITED',
                'cust_code' => '51',
                'address' => 'Gems & Jewellery Park, SDF Block - B, 5th Floor, Ankurhati, Salap, Howrah, West Bengal, 711409',
                'city' => 'Kolkata - 700016',
                'state' => 'West Bengal',
                'phone' => '7828228859',
                'mobile' => null,
                'cont_person' => 'Akash Kajre',
                'gstin' => '19AAACT5131A1ZU',
                'statecode' => '19',
                'is_validation' => 'Yes',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 07:29:50',
            ],
            [
                'id' => 2,
                'party_type' => 'Company',
                'cid' => 'Pritam',
                'cust_name' => 'PRITAM JEWELLERS PVT LTD',
                'cust_code' => '1',
                'address' => '39/4/1 A.K Mukherjee Road, Baranagar, Nowapara, Kolkata - 700090',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'phone' => '9830916917',
                'mobile' => null,
                'cont_person' => 'GAUTAM CHAKRABARTTY',
                'gstin' => '19AAACT5131A1ZU',
                'statecode' => '19',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 06:36:49',
            ],
            [
                'id' => 3,
                'party_type' => 'Customer',
                'cid' => 'AI',
                'cust_name' => 'AURO IMPEX',
                'cust_code' => '2',
                'address' => 'Ground Floor, No.22/11B, Gopal Lay Out, Ponnaiyarajapuram, Coimbatore, Tamil Nadu-641001',
                'city' => 'Coimbatore',
                'state' => 'Tamilnadu',
                'phone' => '9343335916',
                'mobile' => null,
                'cont_person' => 'Promod Kumar',
                'gstin' => '33AOFPC5172G1ZB',
                'statecode' => '33',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => 'Super Admin',
                'created_at' => '2025-11-04 06:35:39',
                'updated_at' => '2025-11-04 06:48:06',
            ],
            [
                'id' => 4,
                'party_type' => 'Customer',
                'cid' => 'ASJL',
                'cust_name' => 'AVR SWARNAMAHAL JEWELRY LIMITED',
                'cust_code' => '3',
                'address' => 'No. 148, 8th Floor, Acropolis, Dr Radhakrishnan Salai, Chennai-600004',
                'city' => 'Chennai',
                'state' => 'Tamilnadu',
                'phone' => '9994073006',
                'mobile' => null,
                'cont_person' => 'Sarbanand',
                'gstin' => '33AAHCA9042L1ZJ',
                'statecode' => '33',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => 'Super Admin',
                'created_at' => '2025-11-04 06:37:09',
                'updated_at' => '2025-11-04 07:48:19',
            ],
            [
                'id' => 5,
                'party_type' => 'Customer',
                'cid' => 'BDB',
                'cust_name' => 'B. D. BANGLES',
                'cust_code' => '4',
                'address' => '1ST FLOOR, OFFICE NO. 109,3/37, PLOT NO. 35,CHANDRA BHAVAN,DHANJI STREET, ZAVERI BAZAR, MUMBAI, Maharashtra-400003',
                'city' => 'MUMBAI',
                'state' => 'Maharashtra',
                'phone' => '9137872874',
                'mobile' => null,
                'cont_person' => 'Syeans Kothari',
                'gstin' => '27AIKPK4172D1ZB',
                'statecode' => '27',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => 'Super Admin',
                'created_at' => '2025-11-04 06:38:36',
                'updated_at' => '2025-11-04 06:47:56',
            ],
            [
                'id' => 6,
                'party_type' => 'Customer',
                'cid' => 'CGPIL',
                'cust_name' => 'CHEMMANUR GOLD PALACE INTERNATIONAL LIMITED',
                'cust_code' => '5',
                'address' => 'GLOBAL VILLAGE, BANK ROAD, KANNUR, Kerala-670002',
                'city' => 'KANNUR',
                'state' => 'Kerala',
                'phone' => '8075919577',
                'mobile' => null,
                'cont_person' => 'Augustin',
                'gstin' => '32AADCC4861D1Z3',
                'statecode' => '32',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => 'Super Admin',
                'created_at' => '2025-11-04 06:40:00',
                'updated_at' => '2025-11-04 06:48:08',
            ],
            [
                'id' => 7,
                'party_type' => 'Customer',
                'cid' => 'DIJPL',
                'cust_name' => 'D.I. JEWELS PVT. LTD.',
                'cust_code' => '6',
                'address' => '10, POLICE LANE, BHADRAKALI, HOOGLY-712232',
                'city' => 'BHADRAKALI',
                'state' => 'West Bengal',
                'phone' => '7003577211',
                'mobile' => null,
                'cont_person' => 'Biswajit',
                'gstin' => '19AAJCP7193D1Z1',
                'statecode' => '19',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => 'Super Admin',
                'created_at' => '2025-11-04 06:41:19',
                'updated_at' => '2025-11-04 07:48:40',
            ],
            [
                'id' => 8,
                'party_type' => 'Customer',
                'cid' => 'DC',
                'cust_name' => 'DURGA CHAIN',
                'cust_code' => '7',
                'address' => 'Plot -3/5, 4A, Ground Floor,Seth Lalji Dayal Building, Dadi Seth Agiary Lane, Dadi Seth Agiary Lane, Kalbadevi, Mumbai, Maharashtra-400002',
                'city' => 'Mumbai',
                'state' => 'Maharashtra',
                'phone' => '7021332032',
                'mobile' => null,
                'cont_person' => 'Dilip Bhai',
                'gstin' => '27ADCPJ8004E1ZY',
                'statecode' => '27',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => 'Super Admin',
                'created_at' => '2025-11-04 06:42:35',
                'updated_at' => '2025-11-04 06:49:06',
            ],
            [
                'id' => 9,
                'party_type' => 'Customer',
                'cid' => 'HKJPL',
                'cust_name' => 'H K JEWELS PRIVATE LIMITED',
                'cust_code' => '8',
                'address' => '17th Floor, G Block, 1701-A, The Capital,Bandra Kurla Complex, Bandra East, Mumbai Suburban, Maharashtra-400051',
                'city' => 'Mumbai',
                'state' => 'Maharashtra',
                'phone' => '9967242801',
                'mobile' => null,
                'cont_person' => 'Mehul Soni',
                'gstin' => '27AACCH2454E1ZV',
                'statecode' => '27',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => 'Super Admin',
                'created_at' => '2025-11-04 06:43:57',
                'updated_at' => '2025-11-04 06:49:19',
            ],
            [
                'id' => 10,
                'party_type' => 'Customer',
                'cid' => 'JCPL',
                'cust_name' => 'JAGDAMBA CHAINS PRIVATE LIMITED',
                'cust_code' => '9',
                'address' => '1st Floor,26, Shop no. 101 Adi Banstalla Lane, Burrabazar, Kolkata-700007',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'phone' => '8420555955',
                'mobile' => null,
                'cont_person' => 'Sourav Soni',
                'gstin' => '19AAKCS2780C1Z8',
                'statecode' => '19',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => 'Super Admin',
                'created_at' => '2025-11-04 06:45:15',
                'updated_at' => '2025-11-04 06:49:34',
            ],
            [
                'id' => 11,
                'party_type' => 'Customer',
                'cid' => 'KJIL',
                'cust_name' => 'KALYAN JEWELLERS INDIA LIMITED',
                'cust_code' => '10',
                'address' => 'DOOR NO - 3B, MANDEVILLE GARDENS, GARIAHAT, KOLKATA-700019',
                'city' => 'KOLKATA',
                'state' => 'West Bengal',
                'phone' => '7044431833',
                'mobile' => null,
                'cont_person' => 'Martin',
                'gstin' => '19AADCK6079K1ZY',
                'statecode' => '19',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => 'Super Admin',
                'created_at' => '2025-11-04 06:49:35',
                'updated_at' => '2025-11-04 06:50:05',
            ],
            [
                'id' => 12,
                'party_type' => 'Customer',
                'cid' => 'LJML',
                'cust_name' => 'LALITHAA JEWELLERY MART LTD.',
                'cust_code' => '11',
                'address' => '53, Icon Savithri Ganesh Building, Habibullah Road, T. Nagar, Chennai, Tamil Nadu-600017',
                'city' => 'Chennai',
                'state' => 'Tamilnadu',
                'phone' => '8668074609',
                'mobile' => null,
                'cont_person' => 'Pappu Bhai',
                'gstin' => '33AAACL1523A1ZG',
                'statecode' => '33',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => 'Super Admin',
                'created_at' => '2025-11-04 06:50:59',
                'updated_at' => '2025-11-04 06:52:38',
            ],
            [
                'id' => 13,
                'party_type' => 'Customer',
                'cid' => 'LI',
                'cust_name' => 'LODHA IMPEX',
                'cust_code' => '12',
                'address' => 'Ground Floor, 28/51, Thandavarayan Street, Tondiarpet, Chennai, Tamil Nadu-600021',
                'city' => 'Chennai',
                'state' => 'Tamilnadu',
                'phone' => '9381010777',
                'mobile' => null,
                'cont_person' => 'Ramesh Bhai',
                'gstin' => '33ADHPR8126N1Z2',
                'statecode' => '33',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => 'Super Admin',
                'created_at' => '2025-11-04 06:52:24',
                'updated_at' => '2025-11-04 06:53:28',
            ],
            [
                'id' => 14,
                'party_type' => 'Customer',
                'cid' => 'MJL',
                'cust_name' => 'MANAPPURAM JEWELLERS LIMITED',
                'cust_code' => '13',
                'address' => 'Kssidc 2nd Phase,Bommasandra Industrial Area,Jigani Link Road, Banglore, Karnataka-560099',
                'city' => 'Banglore',
                'state' => 'Karnataka',
                'phone' => '9945674161',
                'mobile' => null,
                'cont_person' => 'Bijoy',
                'gstin' => '29AAFCM8171J1ZY',
                'statecode' => '29',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => 'Super Admin',
                'created_at' => '2025-11-04 06:53:50',
                'updated_at' => '2025-11-04 06:55:24',
            ],
            [
                'id' => 15,
                'party_type' => 'Customer',
                'cid' => 'PCPL',
                'cust_name' => 'PADMAVATI CHAINS PRIVATE LIMITED',
                'cust_code' => '14',
                'address' => '4th Floor 254/258, S.No. 13 Mansingka Chs Ltd, Kalbadevi Road, Kalbadevi, Mumbai City, Mumbai, Maharashtra-400002',
                'city' => 'Mumbai',
                'state' => 'Maharashtra',
                'phone' => '9821347331',
                'mobile' => null,
                'cont_person' => 'Raju Bhai',
                'gstin' => '27AAFCP7419J1Z2',
                'statecode' => '27',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => 'Super Admin',
                'created_at' => '2025-11-04 06:55:21',
                'updated_at' => '2025-11-04 06:55:43',
            ],
            [
                'id' => 16,
                'party_type' => 'Customer',
                'cid' => 'PNG',
                'cust_name' => 'P N GADGIL',
                'cust_code' => '15',
                'address' => 'SHOWROOM NO. 1 ,, CTS NO. 8/20, PLOT NO. 6/20, GUARDIAN SQUARE, NEAR NISARG HOTEL, ERANDWANE, PUNE, Maharashtra-411004',
                'city' => 'PUNE',
                'state' => 'Maharashtra',
                'phone' => '9850900001',
                'mobile' => null,
                'cont_person' => 'Avay Gadgil',
                'gstin' => '27AAUFP5892R1ZS',
                'statecode' => '27',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => 'Super Admin',
                'created_at' => '2025-11-04 06:57:03',
                'updated_at' => '2025-11-04 07:31:48',
            ],
            [
                'id' => 17,
                'party_type' => 'Customer',
                'cid' => 'RKRJ',
                'cust_name' => 'R.K.R JEWELLERS',
                'cust_code' => '16',
                'address' => '20, MANDAVI, MUMBADEVI, 3RD FLOOR,PLOT NO. 51/55, MOTI BAZAAR, DHANJI STREET, MUMBAI, MAHARASHTRA-400003',
                'city' => 'MUMBAI',
                'state' => 'Maharashtra',
                'phone' => '',
                'mobile' => '9321818554',
                'cont_person' => 'Sanjay Da',
                'gstin' => '27AEHPR2371E1ZH',
                'statecode' => '27',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 07:17:42',
                'updated_at' => '2025-11-04 07:17:42',
            ],
            [
                'id' => 18,
                'party_type' => 'Customer',
                'cid' => 'SGDL',
                'cust_name' => 'SKY GOLD AND DIAMONDS LIMITED',
                'cust_code' => '17',
                'address' => 'PLOT NO. D-222/2, TTC MIDC INDUSTRIAL AREA, SHIRAWANE, NAVI MUMBAI, THANE, Maharashtra-400706',
                'city' => 'NAVI MUMBAI',
                'state' => 'Maharashtra',
                'phone' => '',
                'mobile' => '9820994800',
                'cont_person' => 'Mahindar',
                'gstin' => '27AALCS9127N1ZK',
                'statecode' => '27',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 07:19:29',
                'updated_at' => '2025-11-04 07:19:29',
            ],
            [
                'id' => 19,
                'party_type' => 'Customer',
                'cid' => 'TBZL',
                'cust_name' => 'TRIBHOVANDAS BHIMJI ZAVERI LTD',
                'cust_code' => '18',
                'address' => '241/243, ZAVERI BAZAR, MUMBAI, Maharashtra-400002',
                'city' => 'MUMBAI',
                'state' => 'Maharashtra',
                'phone' => '',
                'mobile' => '8652095788',
                'cont_person' => 'Sandhya',
                'gstin' => '27AACCT7182P1ZL',
                'statecode' => '27',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 07:21:17',
                'updated_at' => '2025-11-04 07:21:17',
            ],
            [
                'id' => 20,
                'party_type' => 'Customer',
                'cid' => 'UCPL',
                'cust_name' => 'UNIQUE CHAINS PVT. LTD',
                'cust_code' => '19',
                'address' => 'Bullion House 2nd Floor, 115, Tambakatta Lane, Mumbadevi Road, Near Hotel Sharada, Mumbai, Maharashtra-400003',
                'city' => 'Mumbai',
                'state' => 'Maharashtra',
                'phone' => '',
                'mobile' => '8657448637',
                'cont_person' => 'Laxmi narayan',
                'gstin' => '27AABCU1931G1ZJ',
                'statecode' => '27',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 07:22:52',
                'updated_at' => '2025-11-04 07:22:52',
            ],
            [
                'id' => 21,
                'party_type' => 'Customer',
                'cid' => 'VJJPL',
                'cust_name' => 'Vijay Raj Jewellers Pvt Ltd',
                'cust_code' => '20',
                'address' => '504,, Plot No 99/103, Bhagwan Bhuvan, Mumbadevi,Madvi, Mumbai Maharashtra-400003',
                'city' => 'Mumbai',
                'state' => 'Maharashtra',
                'phone' => '',
                'mobile' => '9820052103',
                'cont_person' => 'Bijay Bhai',
                'gstin' => '27AAJCV4030H1ZC',
                'statecode' => '27',
                'is_validation' => 'No',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 07:24:28',
                'updated_at' => '2025-11-04 07:24:28',
            ],
        ]);
    }
}
