<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KarigarTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $karigars = [
            [
                'kid' => 'PJDD84',
                'kname' => 'Dulal Das',
                'kfather' => 'Jaladhar Das',
                'address' => 'Banbakhal, Gohalberia, Howrah, West Bengal, 711315',
                'phone' => null,
                'mobile' => '9874977073',
                'pan' => 'BDSPD3126Q',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:17:09',
            ],
            [
                'kid' => 'PJDG85',
                'kname' => 'Debasis Guin',
                'kfather' => 'Sanatan Guin',
                'address' => 'Ward No 02, Ramjibanpur, Paschim Medinipur, West Bengal, 721242',
                'phone' => null,
                'mobile' => '9674150967',
                'pan' => 'BITPG2965A',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:17:42',
            ],
            [
                'kid' => 'PJAP82',
                'kname' => 'Animesh Pramanik',
                'kfather' => 'Ram Pramanik',
                'address' => 'Mato, Howrah, West Bengal, 711408',
                'phone' => null,
                'mobile' => '6289721577',
                'pan' => 'BWFPP4131F',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => null,
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:18:13',
            ],
            [
                'kid' => 'PJPP81',
                'kname' => 'Pappu Patra',
                'kfather' => 'Ramprasad Patra',
                'address' => 'Dahar Kundu, Hoogly, West Bengal, 712617',
                'phone' => null,
                'mobile' => '8617779215',
                'pan' => 'AZXPP7815J',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:18:44',
            ],
            [
                'kid' => 'PJKD88',
                'kname' => 'Kartik Dhara',
                'kfather' => 'Madhusudan Dhara',
                'address' => 'Amberia, Dakshin Shibpur, Shyampur, Ambere, Howrah, West Bengal, 711314',
                'phone' => null,
                'mobile' => '6289586635',
                'pan' => 'CFXPD6024B',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:19:13',
            ],
            [
                'kid' => 'PJSJ88',
                'kname' => 'Subhankar Jana',
                'kfather' => 'Rangalal Jana',
                'address' => 'Gudarbenia, Kamalpur Shyampur, Beniya Hatpara, Deuli, Howrah, West Bengal, 711301',
                'phone' => null,
                'mobile' => '9874484910',
                'pan' => 'AQBPJ8394D',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:22:37',
            ],
            [
                'kid' => 'PJRS83',
                'kname' => 'Rajendra Kumar Sahu',
                'kfather' => 'Jitendra Kumar Sahu',
                'address' => 'Lenka Sahi Ananda Bazar, Sarapur Anandabazar Bhadrak, Odisha, 756116',
                'phone' => null,
                'mobile' => '9330647371',
                'pan' => 'FLXPS2214H',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => null,
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:23:03',
            ],
            [
                'kid' => 'PJSM83',
                'kname' => 'Shambhu Nath Mondal',
                'kfather' => 'Mantu Mondal',
                'address' => 'Karkai, Paschim Medinipur, West Bengal, 721140',
                'phone' => null,
                'mobile' => '9733789658',
                'pan' => 'GSKPM7338K',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:40:50',
            ],
            [
                'kid' => 'PJRP88',
                'kname' => 'Rajesh Patra',
                'kfather' => 'Gobinda Patra',
                'address' => 'Amberia, Dakshin Shibpur, Ambere, Howrah, West Bengal, 711314',
                'phone' => null,
                'mobile' => '9083069765',
                'pan' => 'GHHPP9555F',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:41:14',
            ],
            [
                'kid' => 'PJAS92',
                'kname' => 'Arup Kumar Samanta',
                'kfather' => 'Biswanath Samanta',
                'address' => 'Nijkhayra, Purba Medinipur, Narayanchak, West Bengal, 721154',
                'phone' => null,
                'mobile' => '6289381842',
                'pan' => 'DBZPS0275Q',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:43:03',
            ],
            [
                'kid' => 'PJPM92',
                'kname' => 'Prasun Modak',
                'kfather' => 'Jiten Modak',
                'address' => 'Ranaghat, Bera Kamgachhi, Nadia, West Bengal, 741201',
                'phone' => null,
                'mobile' => '8918218325',
                'pan' => 'CYAPM4987N',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:43:50',
            ],
            [
                'kid' => 'PJBJ77',
                'kname' => 'Bhaskar Jana',
                'kfather' => 'Krishnapada Jana',
                'address' => 'Shibgachhiya, Howrah, West Bengal, 711401',
                'phone' => null,
                'mobile' => '6291309865',
                'pan' => 'AFRPJ4378L',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:45:10',
            ],
            [
                'kid' => 'PJLD91',
                'kname' => 'Lakhsman Das',
                'kfather' => 'Lokesh Das',
                'address' => 'Aishtala, Subhaspally, Ranaghat-I, Nadia, West Bengal, 741201',
                'phone' => null,
                'mobile' => '8250200819',
                'pan' => 'CEMPD7013Q',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:46:12',
            ],
            [
                'kid' => 'PJGM77',
                'kname' => 'Goutam Manik',
                'kfather' => 'Murari Manik',
                'address' => 'Narottampur, Bargram, Howrah, West Bengal, 711312',
                'phone' => null,
                'mobile' => '6290363875',
                'pan' => 'AQLPM3488K',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:47:22',
            ],
            [
                'kid' => 'PJSD86',
                'kname' => 'Sanjay Das',
                'kfather' => 'Mrityunjay Das',
                'address' => 'Arabinda Pally, Kashimpur, North 24 Parganas, West Bengal, 743248',
                'phone' => null,
                'mobile' => '9088647504',
                'pan' => 'ASAPD8890M',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:49:10',
            ],
            [
                'kid' => 'PJBJ82',
                'kname' => 'Bikash Jana',
                'kfather' => 'Himanshu Jana',
                'address' => 'Tripurapur, Bachhri, Howrah, West Bengal, 711312',
                'phone' => null,
                'mobile' => '6290556031',
                'pan' => 'AWGPJ5108E',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:49:39',
            ],
            [
                'kid' => 'PJAH80',
                'kname' => 'Asit Hota',
                'kfather' => 'Dilip Hota',
                'address' => 'Ramjibanpur, Paschim Medinipur, West Bengal, 721242',
                'phone' => null,
                'mobile' => '9875514958',
                'pan' => 'AEOPH5865E',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:50:08',
            ],
            [
                'kid' => 'PJPC84',
                'kname' => 'Pranab Chowdhuri',
                'kfather' => 'Dilip Chowdhuri',
                'address' => 'Jagatpur, Khanakul, Hooghly, 712417',
                'phone' => null,
                'mobile' => '9732591313',
                'pan' => 'AMUPC7399G',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:50:36',
            ],
            [
                'kid' => 'PJHD84',
                'kname' => 'Hemanta Dutta',
                'kfather' => 'Jaydeb Dutta',
                'address' => '35B, T. Road, Vivek Nagar, Titagarh(M), North 24 Parganas, West Bengal, 700119',
                'phone' => null,
                'mobile' => '9330197910',
                'pan' => 'BUUPD1884Q',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:51:00',
            ],
            [
                'kid' => 'PJTD72',
                'kname' => 'Tapan Dolui',
                'kfather' => 'Shreeram Dolui',
                'address' => 'Gopmohol, Manoharpur, Paschim Medinipur, West Bengal, 721212',
                'phone' => null,
                'mobile' => '7699878792',
                'pan' => 'FPQPD2364G',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:51:28',
            ],
            [
                'kid' => 'PJAM84',
                'kname' => 'Asit Mondal',
                'kfather' => 'Batakrishna Mondal',
                'address' => 'Nandanpur, Hooghly, 712417',
                'phone' => null,
                'mobile' => '7003409571',
                'pan' => null,
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => null,
                'updated_by' => 'Super Admin',
                'created_at' => '2025-10-26 00:01:54',
                'updated_at' => '2025-11-04 05:52:16',
            ],
            [
                'kid' => 'PJGD89',
                'kname' => 'Ganesh Dhara',
                'kfather' => 'Jagannath Dhara',
                'address' => 'Amberia, Dakshin Shibpur, Howrah, West Bengal, 711314',
                'phone' => null,
                'mobile' => '9830809751',
                'pan' => 'DVRPD6254A',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => null,
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 05:53:18',
                'updated_at' => '2025-11-04 05:53:18',
            ],
            [
                'kid' => 'PJKP90',
                'kname' => 'Krishnendu Parui',
                'kfather' => 'Sankar Parui',
                'address' => 'Narottampur, Bargram, Howrah, West Bengal, 711312',
                'phone' => null,
                'mobile' => '6290481320',
                'pan' => 'DZEPP3014B',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 05:54:03',
                'updated_at' => '2025-11-04 05:54:03',
            ],
            [
                'kid' => 'PJPM77',
                'kname' => 'Pintu Maity',
                'kfather' => 'Mohan Maiti',
                'address' => 'Gohaldaha Daspara, Guzarpur, Howrah, 711314',
                'phone' => null,
                'mobile' => '9734343120',
                'pan' => 'BIUPM7890K',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => null,
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 05:55:23',
                'updated_at' => '2025-11-04 05:55:23',
            ],
            [
                'kid' => 'PJPG84',
                'kname' => 'Pravash Guriya',
                'kfather' => 'Madan Guriya',
                'address' => 'Guzarpur, Shyampur, Pichhaldaha, Howrah, 711314',
                'phone' => null,
                'mobile' => '8391834156',
                'pan' => 'AWEPG9126B',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 05:56:21',
                'updated_at' => '2025-11-04 05:56:21',
            ],
            [
                'kid' => 'PJSM93',
                'kname' => 'Surajit Majhi',
                'kfather' => 'Uttam Majhi',
                'address' => 'Shyamnabagram, Kasigram, Dhenria, Bardhhaman, West Bengal, 713125',
                'phone' => null,
                'mobile' => '6294563209',
                'pan' => 'CYOPM5153J',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 05:57:03',
                'updated_at' => '2025-11-04 05:57:03',
            ],
            [
                'kid' => 'PJAM88',
                'kname' => 'Anupam Mondal',
                'kfather' => 'Tufan Mondal',
                'address' => 'Bhooyarah, Bhunyera, Howrah, West Bengal, 711312',
                'phone' => null,
                'mobile' => '8420297837',
                'pan' => 'BHGPM0239P',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 05:58:22',
                'updated_at' => '2025-11-04 05:58:22',
            ],
            [
                'kid' => 'PJDB89',
                'kname' => 'Debnath Bera',
                'kfather' => 'Gour Bera',
                'address' => 'Chitnan, Howrah, West Bengal, 711303',
                'phone' => null,
                'mobile' => '7407681644',
                'pan' => 'BDYPB7642B',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => null,
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 05:59:00',
                'updated_at' => '2025-11-04 05:59:00',
            ],
            [
                'kid' => 'PJGD84',
                'kname' => 'Goutam Dey',
                'kfather' => 'Jugal Dey',
                'address' => 'Garhpratapnagar, Ghatal, West Midnapore, West Bengal, 721212',
                'phone' => null,
                'mobile' => '9674469894',
                'pan' => 'BCDPD6029C',
                'remark' => 'ok',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 06:01:16',
                'updated_at' => '2025-11-04 06:01:16',
            ],
            [
                'kid' => 'PJKH94',
                'kname' => 'Kartik Hazra',
                'kfather' => 'Tapan Hazra',
                'address' => 'Sarachi, Bhagabanpur, South 24 Parganas, Magrahat- 1, West Bengal, 743375',
                'phone' => null,
                'mobile' => '8910730960',
                'pan' => null,
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => null,
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 06:02:17',
                'updated_at' => '2025-11-04 06:02:17',
            ],
            [
                'kid' => 'PJNJ73',
                'kname' => 'Nanda Gopal Jana',
                'kfather' => 'Srikanta Jana',
                'address' => 'Tripurapur, Bachhri, Howrah, West Bengal, 711312',
                'phone' => null,
                'mobile' => '6289940095',
                'pan' => 'AFKPJ9220Q',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 06:03:10',
                'updated_at' => '2025-11-04 06:03:10',
            ],
            [
                'kid' => 'PJNR88',
                'kname' => 'Nirmal Rana',
                'kfather' => 'Ashoke Rana',
                'address' => 'Joteghanashyam, Shyamganj, Paschim Medinipur, Daspur- 2, West Bengal, 721153',
                'phone' => null,
                'mobile' => '7044022137',
                'pan' => 'CXNPR7661C',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 06:04:02',
                'updated_at' => '2025-11-04 06:04:02',
            ],
            [
                'kid' => 'PJNJ69',
                'kname' => 'Nisith Chandra Jana',
                'kfather' => 'Gaour Chandra Jana',
                'address' => 'Bidhan Park, Baranagar, Naopara, West Bengal, 700090',
                'phone' => null,
                'mobile' => '9433564259',
                'pan' => null,
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.1',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 06:04:43',
                'updated_at' => '2025-11-04 06:04:43',
            ],
            [
                'kid' => 'PJPD85',
                'kname' => 'Panchanan Das',
                'kfather' => 'Sridam Chandra Das',
                'address' => 'Satpota, Bhagaban Chak, Paschim Medinipur, Daspur- 2, West Bengal, 721153',
                'phone' => null,
                'mobile' => '8597549074',
                'pan' => 'AQXPD4672L',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 06:05:24',
                'updated_at' => '2025-11-04 06:05:24',
            ],
            [
                'kid' => 'PJRA90',
                'kname' => 'Ratan Chandra Adak',
                'kfather' => 'Badal Adak',
                'address' => 'Paikpari, Ballukhat, Purba Medinipur, West Bengal, 721137',
                'phone' => null,
                'mobile' => '9674235236',
                'pan' => 'BCLPA6311C',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 06:06:10',
                'updated_at' => '2025-11-04 06:06:10',
            ],
            [
                'kid' => 'PJSS84',
                'kname' => 'Samir Samanta',
                'kfather' => 'Sambhu Charan Samanta',
                'address' => 'Kolkata - 700090',
                'phone' => null,
                'mobile' => '9830545496',
                'pan' => 'BKWPS0539P',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 06:07:09',
                'updated_at' => '2025-11-04 06:07:09',
            ],
            [
                'kid' => 'PJSJ83',
                'kname' => 'Sougata Jana',
                'kfather' => 'Pratima Jana',
                'address' => 'Purba Khalna, Howrah, West Bengal, 711413',
                'phone' => null,
                'mobile' => '7980482281',
                'pan' => 'AUYPJ3649R',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 06:07:46',
                'updated_at' => '2025-11-04 06:07:46',
            ],
            [
                'kid' => 'PJIH00',
                'kname' => 'Sk Imam Hossain',
                'kfather' => 'Sk Kader Hossain',
                'address' => 'Mohisdanga, Hooghly, West Bengal, 712305',
                'phone' => null,
                'mobile' => '1234567890',
                'pan' => 'BNIPH6771B',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 06:08:49',
                'updated_at' => '2025-11-04 06:08:49',
            ],
            [
                'kid' => 'PJSA84',
                'kname' => 'Somnath Adak',
                'kfather' => 'Shyamapada Adak',
                'address' => 'Berabei, Srirampur, Gangadharpur, Hooghly, West Bengal, 712306',
                'phone' => null,
                'mobile' => '9674944247',
                'pan' => 'BRVPA2103D',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 06:09:48',
                'updated_at' => '2025-11-04 06:09:48',
            ],
            [
                'kid' => 'PJSM92',
                'kname' => 'Srimanta Meur',
                'kfather' => 'Ganesh Meur',
                'address' => 'Sultanpur, Haora, West Bengal, 711226',
                'phone' => null,
                'mobile' => '9088443698',
                'pan' => 'BGZPM0487P',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 06:10:18',
                'updated_at' => '2025-11-04 06:10:18',
            ],
            [
                'kid' => 'PJSM73',
                'kname' => 'Sukumar Malo',
                'kfather' => 'Khagendra Malo',
                'address' => 'Kowgachi, Bibeknagar, Shyamnagar, North 24 Parganas, West Bengal, 743127',
                'phone' => null,
                'mobile' => '1234567890',
                'pan' => 'CHWPM2015G',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => 'OK',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 06:11:42',
                'updated_at' => '2025-11-04 06:11:42',
            ],
            [
                'kid' => 'PJTK90',
                'kname' => 'Tanmay Karar',
                'kfather' => 'Sunil Karar',
                'address' => 'Madaria, Santosh Nagar, Howrah, West Bengal, 711401',
                'phone' => null,
                'mobile' => '9123745664',
                'pan' => 'DKZPK8976H',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 06:12:18',
                'updated_at' => '2025-11-04 06:12:18',
            ],
            [
                'kid' => 'PJTM76',
                'kname' => 'Tapas Maity',
                'kfather' => 'Gopal Maity',
                'address' => 'Uttar Bar, Paschim Medinipur, West Bengal, 721148',
                'phone' => null,
                'mobile' => '1234567890',
                'pan' => 'AOCPM3044A',
                'remark' => 'OK',
                'introducer' => 'SELF',
                'gstin' => null,
                'statecode' => '19',
                'karigar_loss' => '1.5',
                'is_active' => 'Yes',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-11-04 06:13:33',
                'updated_at' => '2025-11-04 06:13:33',
            ],
            [
                'kid' => 'XX', 
                'kname' => 'XX', 
                'kfather' => 'XX', 
                'address' => 'XX', 
                'phone' => '', 
                'mobile' => '1234567890', 
                'pan' => '', 
                'remark' => 'OK', 
                'introducer' => 'SELF', 
                'gstin' => '', 
                'statecode' => '19', 
                'karigar_loss' => null, 
                'is_active' => 'Yes', 
                'created_by' => null, 
                'updated_by' => null, 
                'created_at' => now(), 
                'updated_at' => now()
            ],
        ];

        DB::table('karigars')->insert($karigars);
    }
}