<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KarigarTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('karigars')->insert([
            ['id' => 1, 'kid' => 'PJDD84', 'kname' => 'Dulal Das', 'kfather' => 'Jaladhar Das', 'address' => 'Banbakhal, Gohalberia, Howrah, West Bengal, 711315', 'phone' => '9870000000', 'mobile' => '', 'pan' => 'BDSPD3126Q', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'kid' => 'PJDG85', 'kname' => 'Debasis Guin', 'kfather' => 'Sanatan Guin', 'address' => 'Ward No 02, Ramjibanpur, Paschim Medinipur, West Bengal, 721242', 'phone' => '', 'mobile' => '', 'pan' => 'BITPG2965A', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'kid' => 'PJAP82', 'kname' => 'Animesh Pramanik', 'kfather' => 'Ram Pramanik', 'address' => 'Mato, Howrah, West Bengal, 711408', 'phone' => '6290000000', 'mobile' => '', 'pan' => 'BWFPP4131F', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'kid' => 'PJPP81', 'kname' => 'Pappu Patra', 'kfather' => 'Ramprasad Patra', 'address' => 'Dahar Kundu, Hoogly, West Bengal, 712617', 'phone' => '8620000000', 'mobile' => '', 'pan' => 'AZXPP7815J', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'kid' => 'PJKD88', 'kname' => 'Kartik Dhara', 'kfather' => 'Madhusudan Dhara', 'address' => 'Amberia, Dakshin Shibpur, Shyampur, Ambere, Howrah, West Bengal, 711314', 'phone' => '6290000000', 'mobile' => '', 'pan' => 'CFXPD6024B', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'kid' => 'PJSJ88', 'kname' => 'Subhankar Jana', 'kfather' => 'Rangalal Jana', 'address' => 'Gudarbenia, Kamalpur Shyampur, Beniya Hatpara, Deuli, Howrah, West Bengal, 711301', 'phone' => '9870000000', 'mobile' => '', 'pan' => 'AQBPJ8394D', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'kid' => 'PJRS83', 'kname' => 'Rajendra Kumar Sahu', 'kfather' => 'Jitendra Kumar Sahu', 'address' => 'Lenka Sahi Ananda Bazar, Sarapur Anandabazar Bhadrak, Odisha, 756116', 'phone' => '8780000000', 'mobile' => '', 'pan' => 'FLXPS2214H', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 8, 'kid' => 'PJSM83', 'kname' => 'Shambhu Nath Mondal', 'kfather' => 'Mantu Mondal', 'address' => 'Karkai, Paschim Medinipur, West Bengal, 721140', 'phone' => '9730000000', 'mobile' => '', 'pan' => 'GSKPM7338K', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 9, 'kid' => 'PJRP88', 'kname' => 'Rajesh Patra', 'kfather' => 'Gobinda Patra', 'address' => 'Amberia, Dakshin Shibpur, Ambere, Howrah, West Bengal, 711314', 'phone' => '9080000000', 'mobile' => '', 'pan' => 'GHHPP9555F', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 10, 'kid' => 'PJAS92', 'kname' => 'Arup Kumar Samanta', 'kfather' => 'Biswanath Samanta', 'address' => 'Nijkhayra, Purba Medinipur, Narayanchak, West Bengal, 721154', 'phone' => '6290000000', 'mobile' => '', 'pan' => 'DBZPS0275Q', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 11, 'kid' => 'PJPM92', 'kname' => 'Prasun Modak', 'kfather' => 'Jiten Modak', 'address' => 'Ranaghat, Bera Kamgachhi, Nadia, West Bengal, 741201', 'phone' => '8170000000', 'mobile' => '', 'pan' => 'CYAPM4987N', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 12, 'kid' => 'PJUP86', 'kname' => 'Uttam Pore', 'kfather' => 'Panchu Pore', 'address' => 'Nandanpur, Hoogly, West Bengal, 712417', 'phone' => '9780000000', 'mobile' => '', 'pan' => 'DSPPP2799D', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 13, 'kid' => 'PJBJ77', 'kname' => 'Bhaskar Jana', 'kfather' => 'Krishnapada Jana', 'address' => 'Shibgachhiya, Howrah, West Bengal, 711401', 'phone' => '6290000000', 'mobile' => '', 'pan' => 'AFRPJ4378L', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 14, 'kid' => 'PJLD91', 'kname' => 'Lakhsman Das', 'kfather' => 'Lokesh Das', 'address' => 'Aishtala, Subhaspally, Ranaghat-I, Nadia, West Bengal, 741201', 'phone' => '8250000000', 'mobile' => '', 'pan' => '', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 15, 'kid' => 'PJGM77', 'kname' => 'Goutam Manik', 'kfather' => 'Murari Manik', 'address' => 'Narottampur, Bargram, Howrah, West Bengal, 711312', 'phone' => '6290000000', 'mobile' => '', 'pan' => 'AQLPM3488K', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 16, 'kid' => 'PJKD93', 'kname' => 'Koushik Das', 'kfather' => 'Anik Das', 'address' => 'Antilapara, Anantapur, Howrah, West Bengal, 711301', 'phone' => '6290000000', 'mobile' => '', 'pan' => 'IETPD7118P', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 17, 'kid' => 'PJSD86', 'kname' => 'Sanjay Das', 'kfather' => 'Mrityunjay Das', 'address' => 'Arabinda Pally, Kashimpur, North 24 Parganas, West Bengal, 743248', 'phone' => '9090000000', 'mobile' => '', 'pan' => 'ASAPD8890M', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 18, 'kid' => 'PJBJ82', 'kname' => 'Bikash Jana', 'kfather' => 'Himanshu Jana', 'address' => 'Tripurapur, Bachhri, Howrah, West Bengal, 711312', 'phone' => '6290000000', 'mobile' => '', 'pan' => 'AWGPJ5108E', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 19, 'kid' => 'PJAH80', 'kname' => 'Asit Hota', 'kfather' => 'Dilip Hota', 'address' => '', 'phone' => '9880000000', 'mobile' => '', 'pan' => 'AEOPH5865E', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 20, 'kid' => 'PJPC84', 'kname' => 'Pranab Chowdhuri', 'kfather' => 'Dilip Chowdhuri', 'address' => '', 'phone' => '9730000000', 'mobile' => '', 'pan' => 'AMUPC7399G', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 21, 'kid' => 'PJHD84', 'kname' => 'Hemanta Dutta', 'kfather' => 'Jaydeb Dutta', 'address' => '35B, T. Road, Vivek Nagar, Titagarh(M), North 24 Parganas, West Bengal, 700119', 'phone' => '9330000000', 'mobile' => '', 'pan' => 'BUUPD1884Q', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 22, 'kid' => 'PJTD72', 'kname' => 'Tapan Dolui', 'kfather' => 'Shreeram Dolui', 'address' => 'Gopmohol, Manoharpur, Paschim Medinipur, West Bengal, 721212', 'phone' => '7700000000', 'mobile' => '', 'pan' => '', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 23, 'kid' => 'XX', 'kname' => 'XX', 'kfather' => 'XX', 'address' => 'XX', 'phone' => '', 'mobile' => '1234567890', 'pan' => '', 'remark' => 'OK', 'introducer' => 'SELF', 'gstin' => '', 'statecode' => '19', 'karigar_loss' => null, 'is_active' => 'Yes', 'created_by' => null, 'updated_by' => null, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
