<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PcodesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pcodes')->insert([
            ['code' => '1', 'description' => 'PENDANT & E_RING', 'is_active' => 'Yes'],
            ['code' => '2', 'description' => 'HALF SET', 'is_active' => 'Yes'],
            ['code' => '3', 'description' => 'N + E_RING+ TIKA', 'is_active' => 'Yes'],
            ['code' => '4', 'description' => 'N + E_RING+ TIKA+BANGLE', 'is_active' => 'Yes'],
            ['code' => '6', 'description' => 'N + E_RING+ F_RING', 'is_active' => 'Yes'],
            ['code' => '8', 'description' => 'N + E_RING+ TIKA+ F_RING', 'is_active' => 'Yes'],
            ['code' => 'B', 'description' => 'BRACELET', 'is_active' => 'Yes'],
            ['code' => 'C', 'description' => 'CHAIN', 'is_active' => 'Yes'],
            ['code' => 'D', 'description' => 'DROP EARRING', 'is_active' => 'Yes'],
            ['code' => 'F', 'description' => 'FINGER RING', 'is_active' => 'Yes'],
            ['code' => 'H', 'description' => 'HOOP EAR RING', 'is_active' => 'Yes'],
            ['code' => 'K', 'description' => 'TIKA', 'is_active' => 'Yes'],
            ['code' => 'N', 'description' => 'NECKLACE', 'is_active' => 'Yes'],
            ['code' => 'O', 'description' => 'NATH', 'is_active' => 'Yes'],
            ['code' => 'P', 'description' => 'PENDENT', 'is_active' => 'Yes'],
            ['code' => 'S', 'description' => 'STUD EAR RING', 'is_active' => 'Yes'],
            ['code' => 'V', 'description' => 'BANGLE', 'is_active' => 'Yes'],
            ['code' => 'X', 'description' => 'OTHER', 'is_active' => 'Yes'],
            ['code' => 'Y', 'description' => 'MANGAL SUTRA', 'is_active' => 'Yes'],
            ['code' => 'E', 'description' => 'HARAM', 'is_active' => 'Yes'],
            ['code' => 'W', 'description' => 'WAIST BELT', 'is_active' => 'Yes'],
            ['code' => 'A', 'description' => 'ARMLATE', 'is_active' => 'Yes'],
            ['code' => 'J', 'description' => 'JHUMAKA', 'is_active' => 'Yes'],
            ['code' => '5', 'description' => 'N + E_RING +TIKA + BANGLE + NATH', 'is_active' => 'Yes'],
            ['code' => 'G', 'description' => 'NECKLACE', 'is_active' => 'Yes'],
            ['code' => 'AB', 'description' => 'Accessories - Brooch', 'is_active' => 'Yes'],
            ['code' => 'AC', 'description' => 'Accessories - Cufflinks', 'is_active' => 'Yes'],
            ['code' => 'AK', 'description' => 'Accessories - Kurta Button', 'is_active' => 'Yes'],
            ['code' => 'AO', 'description' => 'Accessories - Others', 'is_active' => 'Yes'],
            ['code' => 'BB', 'description' => 'Bangles - Kids', 'is_active' => 'Yes'],
            ['code' => 'B2', 'description' => 'Bangles - Set of 2', 'is_active' => 'Yes'],
            ['code' => 'B4', 'description' => 'Bangles - Set of 4', 'is_active' => 'Yes'],
            ['code' => 'B6', 'description' => 'Bangles - Set of 6', 'is_active' => 'Yes'],
            ['code' => 'B8', 'description' => 'Bangles - Set of 8', 'is_active' => 'Yes'],
            ['code' => 'BR', 'description' => 'Bangles Single - Ladies', 'is_active' => 'Yes'],
            ['code' => 'TG', 'description' => 'Bracelet - Gents', 'is_active' => 'Yes'],
            ['code' => 'TL', 'description' => 'Bracelet - Ladies', 'is_active' => 'Yes'],
            ['code' => 'TK', 'description' => 'Bracelets - Kids', 'is_active' => 'Yes'],
            ['code' => 'TT', 'description' => 'Bracelets - Tennis', 'is_active' => 'Yes'],
            ['code' => 'CR', 'description' => 'Chain - Faith & Belief', 'is_active' => 'Yes'],
            ['code' => 'CG', 'description' => 'Chains - Generic', 'is_active' => 'Yes'],
            ['code' => 'KB', 'description' => 'Coin - Custom Made', 'is_active' => 'Yes'],
            ['code' => 'K0', 'description' => 'Coins - Brand logo', 'is_active' => 'Yes'],
            ['code' => 'KA', 'description' => 'Coins - Religious', 'is_active' => 'Yes'],
            ['code' => 'EG', 'description' => 'Earring- Single', 'is_active' => 'Yes'],
            ['code' => 'ED', 'description' => 'Earrings - Drop', 'is_active' => 'Yes'],
            ['code' => 'EH', 'description' => 'Earrings - Hoop', 'is_active' => 'Yes'],
            ['code' => 'EK', 'description' => 'Earrings - Kids', 'is_active' => 'Yes'],
            ['code' => 'ES', 'description' => 'Earrings - Stud', 'is_active' => 'Yes'],
            ['code' => 'FM', 'description' => 'Finger Ring - Bands - Gents', 'is_active' => 'Yes'],
            ['code' => 'FW', 'description' => 'Finger Ring - Bands - Ladies', 'is_active' => 'Yes'],
            ['code' => 'FF', 'description' => 'Finger Ring - Faith & Belief', 'is_active' => 'Yes'],
            ['code' => 'FG', 'description' => 'Finger Ring - Gents', 'is_active' => 'Yes'],
            ['code' => 'FK', 'description' => 'Finger Ring - Kids', 'is_active' => 'Yes'],
            ['code' => 'FL', 'description' => 'Finger Ring - Ladies', 'is_active' => 'Yes'],
            ['code' => 'MC', 'description' => 'Mangalsutra - Chain', 'is_active' => 'Yes'],
            ['code' => 'MP', 'description' => 'Mangalsutra - Pendant', 'is_active' => 'Yes'],
            ['code' => 'MS', 'description' => 'Mangalsutra - Regular/Classic', 'is_active' => 'Yes'],
            ['code' => 'MM', 'description' => 'Modern Mangalsutra', 'is_active' => 'Yes'],
            ['code' => 'NC', 'description' => 'Neckwear - Choker', 'is_active' => 'Yes'],
            ['code' => 'NH', 'description' => 'Neckwear - Hasli', 'is_active' => 'Yes'],
            ['code' => 'NT', 'description' => 'Neckwear - Lariat', 'is_active' => 'Yes'],
            ['code' => 'NL', 'description' => 'Neckwear - Long', 'is_active' => 'Yes'],
            ['code' => 'ND', 'description' => 'Neckwear - Necklet (Detachable)', 'is_active' => 'Yes'],
            ['code' => 'NN', 'description' => 'Neckwear - Necklet (Non-Detachable)', 'is_active' => 'Yes'],
            ['code' => 'NU', 'description' => 'Neckwear - Sautoir', 'is_active' => 'Yes'],
            ['code' => 'NS', 'description' => 'Neckwear - Short', 'is_active' => 'Yes'],
            ['code' => 'NR', 'description' => 'Neckwear - String', 'is_active' => 'Yes'],
            ['code' => 'ZR', 'description' => 'Nose - Ring', 'is_active' => 'Yes'],
            ['code' => 'ZS', 'description' => 'Nosepins - Screw', 'is_active' => 'Yes'],
            ['code' => 'ZW', 'description' => 'Nosepins - Wire', 'is_active' => 'Yes'],
            ['code' => 'PL', 'description' => 'Pendant - Ladies', 'is_active' => 'Yes'],
            ['code' => 'PF', 'description' => 'Pendants - Faith & Belief', 'is_active' => 'Yes'],
            ['code' => 'PG', 'description' => 'Pendants - Gents', 'is_active' => 'Yes'],
            ['code' => 'PK', 'description' => 'Pendants - Kids', 'is_active' => 'Yes'],
            ['code' => 'PX', 'description' => 'Pendants - Regional', 'is_active' => 'Yes'],
            ['code' => 'CX', 'description' => 'Regional Chains', 'is_active' => 'Yes'],
            ['code' => 'MX', 'description' => 'Regional Mangalsutra', 'is_active' => 'Yes'],
            ['code' => 'BK', 'description' => 'Single Bangle - Kada - Gents', 'is_active' => 'Yes'],
            ['code' => 'BO', 'description' => 'Single Bangle - Oval - Ladies', 'is_active' => 'Yes'],
            ['code' => 'MT', 'description' => 'Traditional Mangalsutra', 'is_active' => 'Yes'],
            ['code' => 'WA', 'description' => 'Wedding Accessories - Anklet', 'is_active' => 'Yes'],
            ['code' => 'WB', 'description' => 'Wedding Accessories - Bajuband / Armlet', 'is_active' => 'Yes'],
            ['code' => 'WS', 'description' => 'Wedding Accessories - Champasaralu', 'is_active' => 'Yes'],
            ['code' => 'WH', 'description' => 'Wedding Accessories - Haathphool', 'is_active' => 'Yes'],
            ['code' => 'WM', 'description' => 'Wedding Accessories - Mathapatti', 'is_active' => 'Yes'],
            ['code' => 'WN', 'description' => 'Wedding Accessories - Nath', 'is_active' => 'Yes'],
            ['code' => 'WO', 'description' => 'Wedding Accessories - Others', 'is_active' => 'Yes'],
            ['code' => 'WT', 'description' => 'Wedding Accessories - Tikka', 'is_active' => 'Yes'],
            ['code' => 'WR', 'description' => 'Wedding Accessories - Toe Rings', 'is_active' => 'Yes'],
            ['code' => 'WC', 'description' => 'Wedding Accessories - Waist Chains', 'is_active' => 'Yes'],
            ['code' => 'WW', 'description' => 'Wedding Accessories - Waistbelt', 'is_active' => 'Yes'],
            ['code' => 'CY', 'description' => 'Yard Chains', 'is_active' => 'Yes'],
            ['code' => 'L', 'description' => 'ANKLET', 'is_active' => 'Yes'],
        ]);
    }
}
