<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PcodesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pcodes')->insert([
            ['id' => 1, 'code' => '1', 'description' => 'PENDANT & E_RING', 'is_active' => 'Yes'],
            ['id' => 2, 'code' => '2', 'description' => 'HALF SET', 'is_active' => 'Yes'],
            ['id' => 3, 'code' => '3', 'description' => 'N + E_RING+ TIKA', 'is_active' => 'Yes'],
            ['id' => 4, 'code' => '4', 'description' => 'N + E_RING+ TIKA+BANGLE', 'is_active' => 'Yes'],
            ['id' => 5, 'code' => '6', 'description' => 'N + E_RING+ F_RING', 'is_active' => 'Yes'],
            ['id' => 6, 'code' => '8', 'description' => 'N + E_RING+ TIKA+ F_RING', 'is_active' => 'Yes'],
            ['id' => 7, 'code' => 'B', 'description' => 'BRACELET', 'is_active' => 'Yes'],
            ['id' => 8, 'code' => 'C', 'description' => 'CHAIN', 'is_active' => 'Yes'],
            ['id' => 9, 'code' => 'D', 'description' => 'DROP EARRING', 'is_active' => 'Yes'],
            ['id' => 10, 'code' => 'F', 'description' => 'FINGER RING', 'is_active' => 'Yes'],
            ['id' => 11, 'code' => 'H', 'description' => 'HOOP EAR RING', 'is_active' => 'Yes'],
            ['id' => 12, 'code' => 'K', 'description' => 'TIKA', 'is_active' => 'Yes'],
            ['id' => 13, 'code' => 'N', 'description' => 'NECKLACE', 'is_active' => 'Yes'],
            ['id' => 14, 'code' => 'O', 'description' => 'NATH', 'is_active' => 'Yes'],
            ['id' => 15, 'code' => 'P', 'description' => 'PENDENT', 'is_active' => 'Yes'],
            ['id' => 16, 'code' => 'S', 'description' => 'STUD EAR RING', 'is_active' => 'Yes'],
            ['id' => 17, 'code' => 'V', 'description' => 'BANGLE', 'is_active' => 'Yes'],
            ['id' => 18, 'code' => 'X', 'description' => 'OTHER', 'is_active' => 'Yes'],
            ['id' => 19, 'code' => 'Y', 'description' => 'MANGAL SUTRA', 'is_active' => 'Yes'],
            ['id' => 20, 'code' => 'E', 'description' => 'HARAM', 'is_active' => 'Yes'],
            ['id' => 21, 'code' => 'W', 'description' => 'WAIST BELT', 'is_active' => 'Yes'],
            ['id' => 22, 'code' => 'A', 'description' => 'ARMLATE', 'is_active' => 'Yes'],
            ['id' => 23, 'code' => 'J', 'description' => 'JHUMAKA', 'is_active' => 'Yes'],
            ['id' => 24, 'code' => '5', 'description' => 'N + E_RING +TIKA + BANGLE + NATH', 'is_active' => 'Yes'],
            ['id' => 25, 'code' => 'G', 'description' => 'NECKLACE', 'is_active' => 'Yes'],
            ['id' => 26, 'code' => 'AB', 'description' => 'Accessories - Brooch', 'is_active' => 'Yes'],
            ['id' => 27, 'code' => 'AC', 'description' => 'Accessories - Cufflinks', 'is_active' => 'Yes'],
            ['id' => 28, 'code' => 'AK', 'description' => 'Accessories - Kurta Button', 'is_active' => 'Yes'],
            ['id' => 29, 'code' => 'AO', 'description' => 'Accessories - Others', 'is_active' => 'Yes'],
            ['id' => 30, 'code' => 'BB', 'description' => 'Bangles - Kids', 'is_active' => 'Yes'],
            ['id' => 31, 'code' => 'B2', 'description' => 'Bangles - Set of 2', 'is_active' => 'Yes'],
            ['id' => 32, 'code' => 'B4', 'description' => 'Bangles - Set of 4', 'is_active' => 'Yes'],
            ['id' => 33, 'code' => 'B6', 'description' => 'Bangles - Set of 6', 'is_active' => 'Yes'],
            ['id' => 34, 'code' => 'B8', 'description' => 'Bangles - Set of 8', 'is_active' => 'Yes'],
            ['id' => 35, 'code' => 'BR', 'description' => 'Bangles Single - Ladies', 'is_active' => 'Yes'],
            ['id' => 36, 'code' => 'TG', 'description' => 'Bracelet - Gents', 'is_active' => 'Yes'],
            ['id' => 37, 'code' => 'TL', 'description' => 'Bracelet - Ladies', 'is_active' => 'Yes'],
            ['id' => 38, 'code' => 'TK', 'description' => 'Bracelets - Kids', 'is_active' => 'Yes'],
            ['id' => 39, 'code' => 'TT', 'description' => 'Bracelets - Tennis', 'is_active' => 'Yes'],
            ['id' => 40, 'code' => 'CR', 'description' => 'Chain - Faith & Belief', 'is_active' => 'Yes'],
            ['id' => 41, 'code' => 'CG', 'description' => 'Chains - Generic', 'is_active' => 'Yes'],
            ['id' => 42, 'code' => 'KB', 'description' => 'Coin - Custom Made', 'is_active' => 'Yes'],
            ['id' => 43, 'code' => 'K0', 'description' => 'Coins - Brand logo', 'is_active' => 'Yes'],
            ['id' => 44, 'code' => 'KA', 'description' => 'Coins - Religious', 'is_active' => 'Yes'],
            ['id' => 45, 'code' => 'EG', 'description' => 'Earring- Single', 'is_active' => 'Yes'],
            ['id' => 46, 'code' => 'ED', 'description' => 'Earrings - Drop', 'is_active' => 'Yes'],
            ['id' => 47, 'code' => 'EH', 'description' => 'Earrings - Hoop', 'is_active' => 'Yes'],
            ['id' => 48, 'code' => 'EK', 'description' => 'Earrings - Kids', 'is_active' => 'Yes'],
            ['id' => 49, 'code' => 'ES', 'description' => 'Earrings - Stud', 'is_active' => 'Yes'],
            ['id' => 50, 'code' => 'FM', 'description' => 'Finger Ring - Bands - Gents', 'is_active' => 'Yes'],
            ['id' => 51, 'code' => 'FW', 'description' => 'Finger Ring - Bands - Ladies', 'is_active' => 'Yes'],
            ['id' => 52, 'code' => 'FF', 'description' => 'Finger Ring - Faith & Belief', 'is_active' => 'Yes'],
            ['id' => 53, 'code' => 'FG', 'description' => 'Finger Ring - Gents', 'is_active' => 'Yes'],
            ['id' => 54, 'code' => 'FK', 'description' => 'Finger Ring - Kids', 'is_active' => 'Yes'],
            ['id' => 55, 'code' => 'FL', 'description' => 'Finger Ring - Ladies', 'is_active' => 'Yes'],
            ['id' => 56, 'code' => 'MC', 'description' => 'Mangalsutra - Chain', 'is_active' => 'Yes'],
            ['id' => 57, 'code' => 'MP', 'description' => 'Mangalsutra - Pendant', 'is_active' => 'Yes'],
            ['id' => 58, 'code' => 'MS', 'description' => 'Mangalsutra - Regular/Classic', 'is_active' => 'Yes'],
            ['id' => 59, 'code' => 'MM', 'description' => 'Modern Mangalsutra', 'is_active' => 'Yes'],
            ['id' => 60, 'code' => 'NC', 'description' => 'Neckwear - Choker', 'is_active' => 'Yes'],
            ['id' => 61, 'code' => 'NH', 'description' => 'Neckwear - Hasli', 'is_active' => 'Yes'],
            ['id' => 62, 'code' => 'NT', 'description' => 'Neckwear - Lariat', 'is_active' => 'Yes'],
            ['id' => 63, 'code' => 'NL', 'description' => 'Neckwear - Long', 'is_active' => 'Yes'],
            ['id' => 64, 'code' => 'ND', 'description' => 'Neckwear - Necklet (Detachable)', 'is_active' => 'Yes'],
            ['id' => 65, 'code' => 'NN', 'description' => 'Neckwear - Necklet (Non-Detachable)', 'is_active' => 'Yes'],
            ['id' => 66, 'code' => 'NU', 'description' => 'Neckwear - Sautoir', 'is_active' => 'Yes'],
            ['id' => 67, 'code' => 'NS', 'description' => 'Neckwear - Short', 'is_active' => 'Yes'],
            ['id' => 68, 'code' => 'NR', 'description' => 'Neckwear - String', 'is_active' => 'Yes'],
            ['id' => 69, 'code' => 'ZR', 'description' => 'Nose - Ring', 'is_active' => 'Yes'],
            ['id' => 70, 'code' => 'ZS', 'description' => 'Nosepins - Screw', 'is_active' => 'Yes'],
            ['id' => 71, 'code' => 'ZW', 'description' => 'Nosepins - Wire', 'is_active' => 'Yes'],
            ['id' => 72, 'code' => 'PL', 'description' => 'Pendant - Ladies', 'is_active' => 'Yes'],
            ['id' => 73, 'code' => 'PF', 'description' => 'Pendants - Faith & Belief', 'is_active' => 'Yes'],
            ['id' => 74, 'code' => 'PG', 'description' => 'Pendants - Gents', 'is_active' => 'Yes'],
            ['id' => 75, 'code' => 'PK', 'description' => 'Pendants - Kids', 'is_active' => 'Yes'],
            ['id' => 76, 'code' => 'PX', 'description' => 'Pendants - Regional', 'is_active' => 'Yes'],
            ['id' => 77, 'code' => 'CX', 'description' => 'Regional Chains', 'is_active' => 'Yes'],
            ['id' => 78, 'code' => 'MX', 'description' => 'Regional Mangalsutra', 'is_active' => 'Yes'],
            ['id' => 79, 'code' => 'BK', 'description' => 'Single Bangle - Kada - Gents', 'is_active' => 'Yes'],
            ['id' => 80, 'code' => 'BO', 'description' => 'Single Bangle - Oval - Ladies', 'is_active' => 'Yes'],
            ['id' => 81, 'code' => 'MT', 'description' => 'Traditional Mangalsutra', 'is_active' => 'Yes'],
            ['id' => 82, 'code' => 'WA', 'description' => 'Wedding Accessories - Anklet', 'is_active' => 'Yes'],
            ['id' => 83, 'code' => 'WB', 'description' => 'Wedding Accessories - Bajuband / Armlet', 'is_active' => 'Yes'],
            ['id' => 84, 'code' => 'WS', 'description' => 'Wedding Accessories - Champasaralu', 'is_active' => 'Yes'],
            ['id' => 85, 'code' => 'WH', 'description' => 'Wedding Accessories - Haathphool', 'is_active' => 'Yes'],
            ['id' => 86, 'code' => 'WM', 'description' => 'Wedding Accessories - Mathapatti', 'is_active' => 'Yes'],
            ['id' => 87, 'code' => 'WN', 'description' => 'Wedding Accessories - Nath', 'is_active' => 'Yes'],
            ['id' => 88, 'code' => 'WO', 'description' => 'Wedding Accessories - Others', 'is_active' => 'Yes'],
            ['id' => 89, 'code' => 'WT', 'description' => 'Wedding Accessories - Tikka', 'is_active' => 'Yes'],
            ['id' => 90, 'code' => 'WR', 'description' => 'Wedding Accessories - Toe Rings', 'is_active' => 'Yes'],
            ['id' => 91, 'code' => 'WC', 'description' => 'Wedding Accessories - Waist Chains', 'is_active' => 'Yes'],
            ['id' => 92, 'code' => 'WW', 'description' => 'Wedding Accessories - Waistbelt', 'is_active' => 'Yes'],
            ['id' => 93, 'code' => 'CY', 'description' => 'Yard Chains', 'is_active' => 'Yes'],
            ['id' => 94, 'code' => 'L', 'description' => 'ANKLET', 'is_active' => 'Yes'],
        ]);
    }
}
