<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RolePermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('rolepermissions')->insert([
            [
                'id' => 49,
                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'pcodes',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [
                'id' => 50,
                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'uoms',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [
                'id' => 51,
                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'sizes',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [
                'id' => 52,
                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'patterns',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [
                'id' => 53,
                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'stones',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [
                'id' => 54,
                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'customers',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [
                'id' => 55,
                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'karigars',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [
                'id' => 56,
                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'itemdescriptionheaders',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [
                'id' => 57,
                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'products',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [
                'id' => 58,
                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'metals',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [
                'id' => 59,
                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'metalpurities',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [
                'id' => 60,
                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'tollerences',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [
                'id' => 61,
                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'locations',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [
                'id' => 62,
                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'customerordertemps',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [
                'id' => 63,
                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'customerorders',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [
                'id' => 64,
                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'issuetokarigars',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [
                'id' => 65,
                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'pcodes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [
                'id' => 66,
                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'uoms',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [
                'id' => 67,
                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'sizes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [
                'id' => 68,
                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'patterns',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [
                'id' => 69,
                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'stones',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [
                'id' => 70,
                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'customers',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [
                'id' => 71,
                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'karigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [
                'id' => 72,
                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'itemdescriptionheaders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [
                'id' => 73,
                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'products',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [
                'id' => 74,
                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'metals',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [
                'id' => 75,
                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'metalpurities',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [
                'id' => 76,
                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'tollerences',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [
                'id' => 77,
                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'locations',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [
                'id' => 78,
                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'customerordertemps',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [
                'id' => 79,
                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'customerorders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [
                'id' => 80,
                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'issuetokarigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [
                'id' => 81,
                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'pcodes',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [
                'id' => 82,
                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'uoms',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [
                'id' => 83,
                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'sizes',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [
                'id' => 84,
                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'patterns',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [
                'id' => 85,
                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'stones',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [
                'id' => 86,
                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'customers',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [
                'id' => 87,
                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'karigars',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [
                'id' => 88,
                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'itemdescriptionheaders',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [
                'id' => 89,
                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'products',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [
                'id' => 90,
                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'metals',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [
                'id' => 91,
                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'metalpurities',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [
                'id' => 92,
                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'tollerences',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [
                'id' => 93,
                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'locations',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [
                'id' => 94,
                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'customerordertemps',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [
                'id' => 95,
                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'customerorders',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [
                'id' => 96,
                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'issuetokarigars',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [
                'id' => 97,
                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'pcodes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [
                'id' => 98,
                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'uoms',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [
                'id' => 99,
                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'sizes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [
                'id' => 100,
                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'patterns',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [
                'id' => 101,
                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'stones',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [
                'id' => 102,
                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'customers',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [
                'id' => 103,
                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'karigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [
                'id' => 104,
                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'itemdescriptionheaders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [
                'id' => 105,
                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'products',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [
                'id' => 106,
                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'metals',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [
                'id' => 107,
                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'metalpurities',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [
                'id' => 108,
                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'tollerences',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [
                'id' => 109,
                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'locations',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [
                'id' => 110,
                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'customerordertemps',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [
                'id' => 111,
                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'customerorders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [
                'id' => 112,
                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'issuetokarigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [
                'id' => 113,
                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'pcodes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [
                'id' => 114,
                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'uoms',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [
                'id' => 115,
                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'sizes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [
                'id' => 116,
                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'patterns',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [
                'id' => 117,
                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'stones',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [
                'id' => 118,
                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'customers',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [
                'id' => 119,
                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'karigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [
                'id' => 120,
                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'itemdescriptionheaders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [
                'id' => 121,
                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'products',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [
                'id' => 122,
                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'metals',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [
                'id' => 123,
                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'metalpurities',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [
                'id' => 124,
                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'tollerences',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [
                'id' => 125,
                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'locations',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [
                'id' => 126,
                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'customerordertemps',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [
                'id' => 127,
                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'customerorders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [
                'id' => 128,
                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'issuetokarigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [
                'id' => 129,
                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'pcodes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [
                'id' => 130,
                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'uoms',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [
                'id' => 131,
                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'sizes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [
                'id' => 132,
                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'patterns',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [
                'id' => 133,
                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'stones',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [
                'id' => 134,
                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'customers',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [
                'id' => 135,
                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'karigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [
                'id' => 136,
                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'itemdescriptionheaders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [
                'id' => 137,
                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'products',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [
                'id' => 138,
                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'metals',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [
                'id' => 139,
                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'metalpurities',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [
                'id' => 140,
                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'tollerences',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [
                'id' => 141,
                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'locations',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [
                'id' => 142,
                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'customerordertemps',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [
                'id' => 143,
                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'customerorders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [
                'id' => 144,
                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'issuetokarigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [
                'id' => 145,
                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'pcodes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [
                'id' => 146,
                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'uoms',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [
                'id' => 147,
                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'sizes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [
                'id' => 148,
                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'patterns',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [
                'id' => 149,
                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'stones',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [
                'id' => 150,
                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'customers',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [
                'id' => 151,
                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'karigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [
                'id' => 152,
                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'itemdescriptionheaders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [
                'id' => 153,
                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'products',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [
                'id' => 154,
                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'metals',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [
                'id' => 155,
                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'metalpurities',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [
                'id' => 156,
                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'tollerences',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [
                'id' => 157,
                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'locations',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [
                'id' => 158,
                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'customerordertemps',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [
                'id' => 159,
                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'customerorders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [
                'id' => 160,
                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'issuetokarigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [
                'id' => 161,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'pcodes',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [
                'id' => 162,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'uoms',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [
                'id' => 163,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'sizes',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [
                'id' => 164,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'patterns',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [
                'id' => 165,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'stones',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [
                'id' => 166,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'customers',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [
                'id' => 167,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'vendors',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [
                'id' => 168,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'karigars',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [
                'id' => 169,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'itemdescriptionheaders',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [
                'id' => 170,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'products',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [
                'id' => 171,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'metals',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [
                'id' => 172,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'metalpurities',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [
                'id' => 173,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'tollerences',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [
                'id' => 174,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'locations',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [
                'id' => 175,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'customerordertemps',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [
                'id' => 176,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'customerorders',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [
                'id' => 177,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'issuetokarigars',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [
                'id' => 178,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'miscellaneouses',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [
                'id' => 179,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'purchases',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [
                'id' => 180,
                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'sales',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
        ]);
    }
}
