<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RolePermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('rolepermissions')->insert([
            [

                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'pcodes',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'uoms',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'sizes',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'patterns',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'stones',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'customers',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'companies',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'karigars',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'itemdescriptionheaders',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'products',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'metals',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'metalpurities',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'tollerences',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'locations',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'customerordertemps',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'customerorders',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 2,
                'user_id' => 2,
                'menu_name' => 'issuetokarigars',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'pcodes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [

                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'uoms',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [

                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'sizes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [

                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'patterns',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [

                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'stones',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [

                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'customers',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [

                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'companies',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'karigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [

                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'itemdescriptionheaders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [

                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'products',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [

                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'metals',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [

                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'metalpurities',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [

                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'tollerences',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [

                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'locations',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [

                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'customerordertemps',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [

                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'customerorders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [

                'rolepermissionuser_id' => 3,
                'user_id' => 3,
                'menu_name' => 'issuetokarigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:57:42',
                'updated_at' => '2025-08-11 00:57:42',
            ],
            [

                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'pcodes',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [

                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'uoms',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [

                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'sizes',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [

                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'patterns',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [

                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'stones',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [

                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'customers',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [

                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'companies',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'karigars',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [

                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'itemdescriptionheaders',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [

                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'products',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [

                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'metals',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [

                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'metalpurities',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [

                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'tollerences',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [

                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'locations',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [

                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'customerordertemps',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [

                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'customerorders',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [

                'rolepermissionuser_id' => 4,
                'user_id' => 4,
                'menu_name' => 'issuetokarigars',
                'menu_permissions' => '0',
                'permissions_add' => '0',
                'permissions_edit' => '1',
                'permissions_delete' => '0',
                'permissions_view' => '0',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:08',
                'updated_at' => '2025-08-11 00:58:08',
            ],
            [

                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'pcodes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [

                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'uoms',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [

                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'sizes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [

                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'patterns',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [

                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'stones',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [

                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'customers',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [

                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'companies',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'karigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [

                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'itemdescriptionheaders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [

                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'products',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [

                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'metals',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [

                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'metalpurities',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [

                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'tollerences',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [

                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'locations',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [

                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'customerordertemps',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [

                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'customerorders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [

                'rolepermissionuser_id' => 5,
                'user_id' => 5,
                'menu_name' => 'issuetokarigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:36',
                'updated_at' => '2025-08-11 00:58:36',
            ],
            [

                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'pcodes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [

                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'uoms',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [

                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'sizes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [

                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'patterns',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [

                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'stones',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [

                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'customers',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [

                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'companies',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'karigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [

                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'itemdescriptionheaders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [

                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'products',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [

                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'metals',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [

                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'metalpurities',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [

                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'tollerences',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [

                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'locations',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [

                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'customerordertemps',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [

                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'customerorders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [

                'rolepermissionuser_id' => 6,
                'user_id' => 6,
                'menu_name' => 'issuetokarigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:58:53',
                'updated_at' => '2025-08-11 00:58:53',
            ],
            [

                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'pcodes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [

                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'uoms',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [

                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'sizes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [

                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'patterns',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [

                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'stones',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [

                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'customers',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [

                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'companies',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'karigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [

                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'itemdescriptionheaders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [

                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'products',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [

                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'metals',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [

                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'metalpurities',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [

                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'tollerences',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [

                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'locations',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [

                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'customerordertemps',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [

                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'customerorders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [

                'rolepermissionuser_id' => 7,
                'user_id' => 7,
                'menu_name' => 'issuetokarigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:09',
                'updated_at' => '2025-08-11 00:59:09',
            ],
            [

                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'pcodes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [

                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'uoms',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [

                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'sizes',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [

                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'patterns',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [

                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'stones',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [

                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'customers',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [

                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'companies',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-11 00:57:09',
                'updated_at' => '2025-08-11 00:57:09',
            ],
            [

                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'karigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [

                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'itemdescriptionheaders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [

                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'products',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [

                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'metals',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [

                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'metalpurities',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [

                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'tollerences',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [

                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'locations',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [

                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'customerordertemps',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [

                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'customerorders',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [

                'rolepermissionuser_id' => 8,
                'user_id' => 8,
                'menu_name' => 'issuetokarigars',
                'menu_permissions' => '1',
                'permissions_add' => '0',
                'permissions_edit' => '0',
                'permissions_delete' => '0',
                'permissions_view' => '1',
                'permissions_print' => '0',
                'created_at' => '2025-08-11 00:59:24',
                'updated_at' => '2025-08-11 00:59:24',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'pcodes',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'uoms',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'sizes',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'patterns',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'stones',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'customers',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'companies',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'vendors',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'karigars',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'itemdescriptionheaders',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'products',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'metals',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'metalpurities',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'tollerences',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'locations',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'customerordertemps',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'customerorders',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'issuetokarigars',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'miscellaneouses',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'purchases',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
            [

                'rolepermissionuser_id' => 1,
                'user_id' => 1,
                'menu_name' => 'sales',
                'menu_permissions' => '1',
                'permissions_add' => '1',
                'permissions_edit' => '1',
                'permissions_delete' => '1',
                'permissions_view' => '1',
                'permissions_print' => '1',
                'created_at' => '2025-08-15 03:43:17',
                'updated_at' => '2025-08-15 03:43:17',
            ],
        ]);
    }
}
