<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SizesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('sizes')->insert([
            ['pcode_id' => '8', 'schar' => 'S', 'item_name' => 'CHAIN', 'ssize' => '30 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '8', 'schar' => 'J', 'item_name' => 'CHAIN', 'ssize' => '21 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '8', 'schar' => 'F', 'item_name' => 'CHAIN', 'ssize' => '17 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '8', 'schar' => 'G', 'item_name' => 'CHAIN', 'ssize' => '18 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '8', 'schar' => 'H', 'item_name' => 'CHAIN', 'ssize' => '19 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '8', 'schar' => 'K', 'item_name' => 'CHAIN', 'ssize' => '22 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '8', 'schar' => 'L', 'item_name' => 'CHAIN', 'ssize' => '23 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '8', 'schar' => 'M', 'item_name' => 'CHAIN', 'ssize' => '24 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '8', 'schar' => 'N', 'item_name' => 'CHAIN', 'ssize' => '25 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '8', 'schar' => 'P', 'item_name' => 'CHAIN', 'ssize' => '27 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '8', 'schar' => 'Q', 'item_name' => 'CHAIN', 'ssize' => '28 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '8', 'schar' => 'R', 'item_name' => 'CHAIN', 'ssize' => '29 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '8', 'schar' => 'T', 'item_name' => 'CHAIN', 'ssize' => '31 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '8', 'schar' => 'U', 'item_name' => 'CHAIN', 'ssize' => '32 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '8', 'schar' => 'X', 'item_name' => 'CHAIN', 'ssize' => '35 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '8', 'schar' => 'Y', 'item_name' => 'CHAIN', 'ssize' => '36 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '8', 'schar' => 'Z', 'item_name' => 'CHAIN', 'ssize' => '37 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '8', 'schar' => 'I', 'item_name' => 'CHAIN', 'ssize' => '20 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '10', 'schar' => 'F', 'item_name' => 'RING', 'ssize' => '14.00 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '10', 'schar' => 'G', 'item_name' => 'RING', 'ssize' => '14.40 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '10', 'schar' => 'H', 'item_name' => 'RING', 'ssize' => '14.80 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '10', 'schar' => 'I', 'item_name' => 'RING', 'ssize' => '15.20 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '10', 'schar' => 'K', 'item_name' => 'RING', 'ssize' => '16.00 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '10', 'schar' => 'L', 'item_name' => 'RING', 'ssize' => '16.40 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '10', 'schar' => 'M', 'item_name' => 'RING', 'ssize' => '16.80 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '10', 'schar' => 'N', 'item_name' => 'RING', 'ssize' => '17.20 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '10', 'schar' => 'P', 'item_name' => 'RING', 'ssize' => '18.00 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '10', 'schar' => 'R', 'item_name' => 'RING', 'ssize' => '18.80 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '10', 'schar' => 'T', 'item_name' => 'RING', 'ssize' => '19.50 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '10', 'schar' => 'U', 'item_name' => 'RING', 'ssize' => '19.90 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '17', 'schar' => 'W', 'item_name' => 'ROUND BANGLE', 'ssize' => '72.50 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '10', 'schar' => 'X', 'item_name' => 'RING', 'ssize' => '21.10 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '10', 'schar' => 'Y', 'item_name' => 'RING', 'ssize' => '21.50 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '10', 'schar' => 'Z', 'item_name' => 'RING', 'ssize' => '21.90 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '17', 'schar' => 'M', 'item_name' => 'ROUND BANGLE', 'ssize' => '42.00 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '17', 'schar' => 'N', 'item_name' => 'ROUND BANGLE', 'ssize' => '50.00 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '17', 'schar' => 'P', 'item_name' => 'ROUND BANGLE', 'ssize' => '55.00 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '17', 'schar' => 'R', 'item_name' => 'ROUND BANGLE', 'ssize' => '60.00 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '17', 'schar' => 'T', 'item_name' => 'ROUND BANGLE', 'ssize' => '65.00 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '17', 'schar' => 'U', 'item_name' => 'ROUND BANGLE', 'ssize' => '67.50 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '17', 'schar' => 'V', 'item_name' => 'ROUND BANGLE', 'ssize' => '70.00 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '17', 'schar' => 'X', 'item_name' => 'ROUND BANGLE', 'ssize' => '75.00 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '17', 'schar' => 'Y', 'item_name' => 'ROUND BANGLE', 'ssize' => '80.00 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '17', 'schar' => 'F', 'item_name' => 'OVAL BANGLE', 'ssize' => '53*60 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '17', 'schar' => 'G', 'item_name' => 'OVAL BANGLE', 'ssize' => '50*59 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '17', 'schar' => 'O', 'item_name' => 'ROUND BANGLE', 'ssize' => '52.50 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '7', 'schar' => 'F', 'item_name' => 'BRACETET', 'ssize' => '20.00 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '7', 'schar' => 'G', 'item_name' => 'BRACETET', 'ssize' => '20.50 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '7', 'schar' => 'H', 'item_name' => 'BRACETET', 'ssize' => '21.00 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '7', 'schar' => 'I', 'item_name' => 'BRACETET', 'ssize' => '21.50 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '17', 'schar' => 'Q', 'item_name' => 'ROUND BANGLE', 'ssize' => '57.50 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '7', 'schar' => 'K', 'item_name' => 'BRACETET', 'ssize' => '22.50 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '7', 'schar' => 'L', 'item_name' => 'BRACETET', 'ssize' => '23.00 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '7', 'schar' => 'M', 'item_name' => 'BRACETET', 'ssize' => '23.50 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '7', 'schar' => 'N', 'item_name' => 'BRACETET', 'ssize' => '24.00 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '7', 'schar' => 'P', 'item_name' => 'BRACETET', 'ssize' => '12.50 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '7', 'schar' => 'R', 'item_name' => 'BRACETET', 'ssize' => '13.50 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '7', 'schar' => 'T', 'item_name' => 'BRACETET', 'ssize' => '14.50 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '7', 'schar' => 'U', 'item_name' => 'BRACETET', 'ssize' => '15.00 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '7', 'schar' => 'X', 'item_name' => 'BRACETET', 'ssize' => '16.50 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '7', 'schar' => 'Y', 'item_name' => 'BRACETET', 'ssize' => '17.00 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '7', 'schar' => 'Z', 'item_name' => 'BRACETET', 'ssize' => '17.50 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '8', 'schar' => 'O', 'item_name' => 'CHAIN', 'ssize' => '26 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '17', 'schar' => 'S', 'item_name' => 'ROUND BANGLE', 'ssize' => '62.50 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '10', 'schar' => 'O', 'item_name' => 'RING', 'ssize' => '17.60 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '8', 'schar' => 'E', 'item_name' => 'CHAIN', 'ssize' => '16 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'A', 'item_name' => 'Chains - Generic', 'ssize' => '12 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'B', 'item_name' => 'Chains - Generic', 'ssize' => '14 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'C', 'item_name' => 'Chains - Generic', 'ssize' => '15 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'D', 'item_name' => 'Chains - Generic', 'ssize' => '15.5 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'E', 'item_name' => 'Chains - Generic', 'ssize' => '16 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'F', 'item_name' => 'Chains - Generic', 'ssize' => '16.5 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'G', 'item_name' => 'Chains - Generic', 'ssize' => '17 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'H', 'item_name' => 'Chains - Generic', 'ssize' => '18 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'I', 'item_name' => 'Chains - Generic', 'ssize' => '19 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'J', 'item_name' => 'Chains - Generic', 'ssize' => '20 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'K', 'item_name' => 'Chains - Generic', 'ssize' => '22 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'L', 'item_name' => 'Chains - Generic', 'ssize' => '24 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'M', 'item_name' => 'Chains - Generic', 'ssize' => '26 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'N', 'item_name' => 'Chains - Generic', 'ssize' => '28 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'O', 'item_name' => 'Chains - Generic', 'ssize' => '30 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'P', 'item_name' => 'Chains - Generic', 'ssize' => '32 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'Q', 'item_name' => 'Chains - Generic', 'ssize' => '34 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'R', 'item_name' => 'Chains - Generic', 'ssize' => '36 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'S', 'item_name' => 'Chains - Generic', 'ssize' => '38 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'T', 'item_name' => 'Chains - Generic', 'ssize' => '40 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'U', 'item_name' => 'Chains - Generic', 'ssize' => '42 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'V', 'item_name' => 'Chains - Generic', 'ssize' => '44 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'W', 'item_name' => 'Chains - Generic', 'ssize' => '46 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'A', 'item_name' => 'Regional Chains', 'ssize' => '12 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'B', 'item_name' => 'Regional Chains', 'ssize' => '14 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'C', 'item_name' => 'Regional Chains', 'ssize' => '15 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'D', 'item_name' => 'Regional Chains', 'ssize' => '15.5 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'E', 'item_name' => 'Regional Chains', 'ssize' => '16 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'F', 'item_name' => 'Regional Chains', 'ssize' => '16.5 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'G', 'item_name' => 'Regional Chains', 'ssize' => '17 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'H', 'item_name' => 'Regional Chains', 'ssize' => '18 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'I', 'item_name' => 'Regional Chains', 'ssize' => '19 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'J', 'item_name' => 'Regional Chains', 'ssize' => '20 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'K', 'item_name' => 'Regional Chains', 'ssize' => '22 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'L', 'item_name' => 'Regional Chains', 'ssize' => '24 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'M', 'item_name' => 'Regional Chains', 'ssize' => '26 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'N', 'item_name' => 'Regional Chains', 'ssize' => '28 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'O', 'item_name' => 'Regional Chains', 'ssize' => '30 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'P', 'item_name' => 'Regional Chains', 'ssize' => '32 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'Q', 'item_name' => 'Regional Chains', 'ssize' => '34 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'R', 'item_name' => 'Regional Chains', 'ssize' => '36 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'S', 'item_name' => 'Regional Chains', 'ssize' => '38 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'T', 'item_name' => 'Regional Chains', 'ssize' => '40 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'U', 'item_name' => 'Regional Chains', 'ssize' => '42 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'V', 'item_name' => 'Regional Chains', 'ssize' => '44 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'W', 'item_name' => 'Regional Chains', 'ssize' => '46 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '35', 'schar' => 'G', 'item_name' => 'Bangles Single - Ladies', 'ssize' => '50.8 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '35', 'schar' => 'H', 'item_name' => 'Bangles Single - Ladies', 'ssize' => '52.4 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '35', 'schar' => 'I', 'item_name' => 'Bangles Single - Ladies', 'ssize' => '54 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '35', 'schar' => 'J', 'item_name' => 'Bangles Single - Ladies', 'ssize' => '55.5 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '35', 'schar' => 'K', 'item_name' => 'Bangles Single - Ladies', 'ssize' => '57.15 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '35', 'schar' => 'L', 'item_name' => 'Bangles Single - Ladies', 'ssize' => '58.7 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '35', 'schar' => 'M', 'item_name' => 'Bangles Single - Ladies', 'ssize' => '60.3 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '35', 'schar' => 'N', 'item_name' => 'Bangles Single - Ladies', 'ssize' => '61.7 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '35', 'schar' => 'O', 'item_name' => 'Bangles Single - Ladies', 'ssize' => '63.5 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '35', 'schar' => 'P', 'item_name' => 'Bangles Single - Ladies', 'ssize' => '65 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '35', 'schar' => 'Q', 'item_name' => 'Bangles Single - Ladies', 'ssize' => '66.7 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '35', 'schar' => 'R', 'item_name' => 'Bangles Single - Ladies', 'ssize' => '69 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '31', 'schar' => 'G', 'item_name' => 'BANGLES ST2', 'ssize' => '50.8 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '31', 'schar' => 'H', 'item_name' => 'BANGLES ST2', 'ssize' => '52.4 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '31', 'schar' => 'I', 'item_name' => 'BANGLES ST2', 'ssize' => '54 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '31', 'schar' => 'J', 'item_name' => 'BANGLES ST2', 'ssize' => '55.5 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '31', 'schar' => 'K', 'item_name' => 'BANGLES ST2', 'ssize' => '57.15 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '31', 'schar' => 'L', 'item_name' => 'BANGLES ST2', 'ssize' => '58.7 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '31', 'schar' => 'M', 'item_name' => 'BANGLES ST2', 'ssize' => '60.3 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '31', 'schar' => 'N', 'item_name' => 'BANGLES ST2', 'ssize' => '61.7 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '31', 'schar' => 'O', 'item_name' => 'BANGLES ST2', 'ssize' => '63.5 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '31', 'schar' => 'P', 'item_name' => 'BANGLES ST2', 'ssize' => '65 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '31', 'schar' => 'Q', 'item_name' => 'BANGLES ST2', 'ssize' => '66.7 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '31', 'schar' => 'R', 'item_name' => 'BANGLES ST2', 'ssize' => '69 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '32', 'schar' => 'G', 'item_name' => 'BANGLES ST4', 'ssize' => '50.8 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '32', 'schar' => 'H', 'item_name' => 'BANGLES ST4', 'ssize' => '52.4 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '32', 'schar' => 'I', 'item_name' => 'BANGLES ST4', 'ssize' => '54 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '32', 'schar' => 'J', 'item_name' => 'BANGLES ST4', 'ssize' => '55.5 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '32', 'schar' => 'K', 'item_name' => 'BANGLES ST4', 'ssize' => '57.15 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '32', 'schar' => 'L', 'item_name' => 'BANGLES ST4', 'ssize' => '58.7 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '32', 'schar' => 'M', 'item_name' => 'BANGLES ST4', 'ssize' => '60.3 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '32', 'schar' => 'N', 'item_name' => 'BANGLES ST4', 'ssize' => '61.7 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '32', 'schar' => 'O', 'item_name' => 'BANGLES ST4', 'ssize' => '63.5 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '32', 'schar' => 'P', 'item_name' => 'BANGLES ST4', 'ssize' => '65 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '32', 'schar' => 'Q', 'item_name' => 'BANGLES ST4', 'ssize' => '66.7 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '32', 'schar' => 'R', 'item_name' => 'BANGLES ST4', 'ssize' => '69 MM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'A', 'item_name' => 'Bracelet - Gents', 'ssize' => '10.6 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'B', 'item_name' => 'Bracelet - Gents', 'ssize' => '11.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'C', 'item_name' => 'Bracelet - Gents', 'ssize' => '12 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'D', 'item_name' => 'Bracelet - Gents', 'ssize' => '12.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'E', 'item_name' => 'Bracelet - Gents', 'ssize' => '13 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'F', 'item_name' => 'Bracelet - Gents', 'ssize' => '13.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'G', 'item_name' => 'Bracelet - Gents', 'ssize' => '14 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'H', 'item_name' => 'Bracelet - Gents', 'ssize' => '14.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'I', 'item_name' => 'Bracelet - Gents', 'ssize' => '15 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'J', 'item_name' => 'Bracelet - Gents', 'ssize' => '15.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'K', 'item_name' => 'Bracelet - Gents', 'ssize' => '16 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'L', 'item_name' => 'Bracelet - Gents', 'ssize' => '16.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'M', 'item_name' => 'Bracelet - Gents', 'ssize' => '17 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'N', 'item_name' => 'Bracelet - Gents', 'ssize' => '17.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'O', 'item_name' => 'Bracelet - Gents', 'ssize' => '18 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'P', 'item_name' => 'Bracelet - Gents', 'ssize' => '18.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'Q', 'item_name' => 'Bracelet - Gents', 'ssize' => '19 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'R', 'item_name' => 'Bracelet - Gents', 'ssize' => '19.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'S', 'item_name' => 'Bracelet - Gents', 'ssize' => '20 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'T', 'item_name' => 'Bracelet - Gents', 'ssize' => '20.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'U', 'item_name' => 'Bracelet - Gents', 'ssize' => '21 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'V', 'item_name' => 'Bracelet - Gents', 'ssize' => '21.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '36', 'schar' => 'W', 'item_name' => 'Bracelet - Gents', 'ssize' => '22 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'A', 'item_name' => 'Bracelet - Ladies', 'ssize' => '10.6 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'B', 'item_name' => 'Bracelet - Ladies', 'ssize' => '11.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'C', 'item_name' => 'Bracelet - Ladies', 'ssize' => '12 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'D', 'item_name' => 'Bracelet - Ladies', 'ssize' => '12.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'E', 'item_name' => 'Bracelet - Ladies', 'ssize' => '13 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'F', 'item_name' => 'Bracelet - Ladies', 'ssize' => '13.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'G', 'item_name' => 'Bracelet - Ladies', 'ssize' => '14 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'H', 'item_name' => 'Bracelet - Ladies', 'ssize' => '14.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'I', 'item_name' => 'Bracelet - Ladies', 'ssize' => '15 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'J', 'item_name' => 'Bracelet - Ladies', 'ssize' => '15.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'K', 'item_name' => 'Bracelet - Ladies', 'ssize' => '16 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'L', 'item_name' => 'Bracelet - Ladies', 'ssize' => '16.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'M', 'item_name' => 'Bracelet - Ladies', 'ssize' => '17 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'N', 'item_name' => 'Bracelet - Ladies', 'ssize' => '17.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'O', 'item_name' => 'Bracelet - Ladies', 'ssize' => '18 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'P', 'item_name' => 'Bracelet - Ladies', 'ssize' => '18.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'Q', 'item_name' => 'Bracelet - Ladies', 'ssize' => '19 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'R', 'item_name' => 'Bracelet - Ladies', 'ssize' => '19.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'S', 'item_name' => 'Bracelet - Ladies', 'ssize' => '20 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'T', 'item_name' => 'Bracelet - Ladies', 'ssize' => '20.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'U', 'item_name' => 'Bracelet - Ladies', 'ssize' => '21 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'V', 'item_name' => 'Bracelet - Ladies', 'ssize' => '21.5 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '37', 'schar' => 'W', 'item_name' => 'Bracelet - Ladies', 'ssize' => '22 CM', 'is_active' => 'Yes'],
            ['pcode_id' => '41', 'schar' => 'X', 'item_name' => 'Chains - Generic', 'ssize' => '56 INCHES', 'is_active' => 'Yes'],
            ['pcode_id' => '77', 'schar' => 'X', 'item_name' => 'Regional Chains', 'ssize' => '56 INCHES', 'is_active' => 'Yes']
        ]);
    }
}
