<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SizesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('sizes')->insert([
            ['id' => 1, 'pcode_id' => 26, 'schar' => 'A', 'item_name' => 'BANGLE', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 2, 'pcode_id' => 26, 'schar' => 'M', 'item_name' => 'BANGLE', 'ssize' => '42.00 MM', 'is_active' => 'Yes'],
            ['id' => 3, 'pcode_id' => 26, 'schar' => 'N', 'item_name' => 'BANGLE', 'ssize' => '50.00 MM', 'is_active' => 'Yes'],
            ['id' => 4, 'pcode_id' => 26, 'schar' => 'O', 'item_name' => 'BANGLE', 'ssize' => '52.50 MM', 'is_active' => 'Yes'],
            ['id' => 5, 'pcode_id' => 26, 'schar' => 'P', 'item_name' => 'BANGLE', 'ssize' => '55.00 MM', 'is_active' => 'Yes'],
            ['id' => 6, 'pcode_id' => 26, 'schar' => 'Q', 'item_name' => 'BANGLE', 'ssize' => '57.50 MM', 'is_active' => 'Yes'],
            ['id' => 7, 'pcode_id' => 26, 'schar' => 'R', 'item_name' => 'BANGLE', 'ssize' => '60.00 MM', 'is_active' => 'Yes'],
            ['id' => 8, 'pcode_id' => 26, 'schar' => 'S', 'item_name' => 'BANGLE', 'ssize' => '62.50 MM', 'is_active' => 'Yes'],
            ['id' => 9, 'pcode_id' => 26, 'schar' => 'T', 'item_name' => 'BANGLE', 'ssize' => '65.00 MM', 'is_active' => 'Yes'],
            ['id' => 10, 'pcode_id' => 26, 'schar' => 'U', 'item_name' => 'BANGLE', 'ssize' => '67.50 MM', 'is_active' => 'Yes'],
            ['id' => 11, 'pcode_id' => 26, 'schar' => 'V', 'item_name' => 'BANGLE', 'ssize' => '70.00 MM', 'is_active' => 'Yes'],
            ['id' => 12, 'pcode_id' => 26, 'schar' => 'X', 'item_name' => 'BANGLE', 'ssize' => '75.00 MM', 'is_active' => 'Yes'],
            ['id' => 13, 'pcode_id' => 26, 'schar' => 'Y', 'item_name' => 'BANGLE', 'ssize' => '80.00 MM', 'is_active' => 'Yes'],
            ['id' => 14, 'pcode_id' => 12, 'schar' => 'A', 'item_name' => 'BRACELET', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 15, 'pcode_id' => 12, 'schar' => 'F', 'item_name' => 'BRACELET', 'ssize' => '20.00 CM', 'is_active' => 'Yes'],
            ['id' => 16, 'pcode_id' => 12, 'schar' => 'G', 'item_name' => 'BRACELET', 'ssize' => '20.50 CM', 'is_active' => 'Yes'],
            ['id' => 17, 'pcode_id' => 12, 'schar' => 'H', 'item_name' => 'BRACELET', 'ssize' => '21.00 CM', 'is_active' => 'Yes'],
            ['id' => 18, 'pcode_id' => 12, 'schar' => 'I', 'item_name' => 'BRACELET', 'ssize' => '21.50 CM', 'is_active' => 'Yes'],
            ['id' => 19, 'pcode_id' => 12, 'schar' => 'K', 'item_name' => 'BRACELET', 'ssize' => '22.50 CM', 'is_active' => 'Yes'],
            ['id' => 20, 'pcode_id' => 12, 'schar' => 'L', 'item_name' => 'BRACELET', 'ssize' => '23.00 CM', 'is_active' => 'Yes'],
            ['id' => 21, 'pcode_id' => 12, 'schar' => 'M', 'item_name' => 'BRACELET', 'ssize' => '23.50 CM', 'is_active' => 'Yes'],
            ['id' => 22, 'pcode_id' => 12, 'schar' => 'N', 'item_name' => 'BRACELET', 'ssize' => '24.00 CM', 'is_active' => 'Yes'],
            ['id' => 23, 'pcode_id' => 12, 'schar' => 'P', 'item_name' => 'BRACELET', 'ssize' => '12.50 CM', 'is_active' => 'Yes'],
            ['id' => 24, 'pcode_id' => 12, 'schar' => 'R', 'item_name' => 'BRACELET', 'ssize' => '13.50 CM', 'is_active' => 'Yes'],
            ['id' => 25, 'pcode_id' => 12, 'schar' => 'T', 'item_name' => 'BRACELET', 'ssize' => '14.50 CM', 'is_active' => 'Yes'],
            ['id' => 26, 'pcode_id' => 12, 'schar' => 'U', 'item_name' => 'BRACELET', 'ssize' => '15.00 CM', 'is_active' => 'Yes'],
            ['id' => 27, 'pcode_id' => 12, 'schar' => 'X', 'item_name' => 'BRACELET', 'ssize' => '16.50 CM', 'is_active' => 'Yes'],
            ['id' => 28, 'pcode_id' => 12, 'schar' => 'Y', 'item_name' => 'BRACELET', 'ssize' => '17.00 CM', 'is_active' => 'Yes'],
            ['id' => 29, 'pcode_id' => 12, 'schar' => 'Z', 'item_name' => 'BRACELET', 'ssize' => '17.50 CM', 'is_active' => 'Yes'],
            ['id' => 30, 'pcode_id' => 13, 'schar' => 'A', 'item_name' => 'CHAIN', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 31, 'pcode_id' => 13, 'schar' => 'F', 'item_name' => 'CHAIN', 'ssize' => '17 INCHES', 'is_active' => 'Yes'],
            ['id' => 32, 'pcode_id' => 13, 'schar' => 'G', 'item_name' => 'CHAIN', 'ssize' => '18 INCHES', 'is_active' => 'Yes'],
            ['id' => 33, 'pcode_id' => 13, 'schar' => 'H', 'item_name' => 'CHAIN', 'ssize' => '19 INCHES', 'is_active' => 'Yes'],
            ['id' => 34, 'pcode_id' => 13, 'schar' => 'I', 'item_name' => 'CHAIN', 'ssize' => '20 INCHES', 'is_active' => 'Yes'],
            ['id' => 35, 'pcode_id' => 13, 'schar' => 'J', 'item_name' => 'CHAIN', 'ssize' => '21 INCHES', 'is_active' => 'Yes'],
            ['id' => 36, 'pcode_id' => 13, 'schar' => 'K', 'item_name' => 'CHAIN', 'ssize' => '22 INCHES', 'is_active' => 'Yes'],
            ['id' => 37, 'pcode_id' => 13, 'schar' => 'L', 'item_name' => 'CHAIN', 'ssize' => '23 INCHES', 'is_active' => 'Yes'],
            ['id' => 38, 'pcode_id' => 13, 'schar' => 'M', 'item_name' => 'CHAIN', 'ssize' => '24 INCHES', 'is_active' => 'Yes'],
            ['id' => 39, 'pcode_id' => 13, 'schar' => 'N', 'item_name' => 'CHAIN', 'ssize' => '25 INCHES', 'is_active' => 'Yes'],
            ['id' => 40, 'pcode_id' => 13, 'schar' => 'O', 'item_name' => 'CHAIN', 'ssize' => '26 INCHES', 'is_active' => 'Yes'],
            ['id' => 41, 'pcode_id' => 13, 'schar' => 'P', 'item_name' => 'CHAIN', 'ssize' => '27 INCHES', 'is_active' => 'Yes'],
            ['id' => 42, 'pcode_id' => 13, 'schar' => 'Q', 'item_name' => 'CHAIN', 'ssize' => '28 INCHES', 'is_active' => 'Yes'],
            ['id' => 43, 'pcode_id' => 13, 'schar' => 'R', 'item_name' => 'CHAIN', 'ssize' => '29 INCHES', 'is_active' => 'Yes'],
            ['id' => 44, 'pcode_id' => 13, 'schar' => 'S', 'item_name' => 'CHAIN', 'ssize' => '30 INCHES', 'is_active' => 'Yes'],
            ['id' => 45, 'pcode_id' => 13, 'schar' => 'T', 'item_name' => 'CHAIN', 'ssize' => '31 INCHES', 'is_active' => 'Yes'],
            ['id' => 46, 'pcode_id' => 13, 'schar' => 'U', 'item_name' => 'CHAIN', 'ssize' => '32 INCHES', 'is_active' => 'Yes'],
            ['id' => 47, 'pcode_id' => 16, 'schar' => 'A', 'item_name' => 'FINGERRING', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 48, 'pcode_id' => 16, 'schar' => 'F', 'item_name' => 'FINGERRING', 'ssize' => '14.00 MM', 'is_active' => 'Yes'],
            ['id' => 49, 'pcode_id' => 16, 'schar' => 'G', 'item_name' => 'FINGERRING', 'ssize' => '14.40 MM', 'is_active' => 'Yes'],
            ['id' => 50, 'pcode_id' => 16, 'schar' => 'H', 'item_name' => 'FINGERRING', 'ssize' => '14.80 MM', 'is_active' => 'Yes'],
            ['id' => 51, 'pcode_id' => 16, 'schar' => 'I', 'item_name' => 'FINGERRING', 'ssize' => '15.20 MM', 'is_active' => 'Yes'],
            ['id' => 52, 'pcode_id' => 16, 'schar' => 'K', 'item_name' => 'FINGERRING', 'ssize' => '16.00 MM', 'is_active' => 'Yes'],
            ['id' => 53, 'pcode_id' => 16, 'schar' => 'L', 'item_name' => 'FINGERRING', 'ssize' => '16.40 MM', 'is_active' => 'Yes'],
            ['id' => 54, 'pcode_id' => 16, 'schar' => 'M', 'item_name' => 'FINGERRING', 'ssize' => '16.80 MM', 'is_active' => 'Yes'],
            ['id' => 55, 'pcode_id' => 16, 'schar' => 'N', 'item_name' => 'FINGERRING', 'ssize' => '17.20 MM', 'is_active' => 'Yes'],
            ['id' => 56, 'pcode_id' => 16, 'schar' => 'O', 'item_name' => 'FINGERRING', 'ssize' => '17.60 MM', 'is_active' => 'Yes'],
            ['id' => 57, 'pcode_id' => 16, 'schar' => 'P', 'item_name' => 'FINGERRING', 'ssize' => '18.00 MM', 'is_active' => 'Yes'],
            ['id' => 58, 'pcode_id' => 16, 'schar' => 'R', 'item_name' => 'FINGERRING', 'ssize' => '18.80 MM', 'is_active' => 'Yes'],
            ['id' => 59, 'pcode_id' => 16, 'schar' => 'T', 'item_name' => 'FINGERRING', 'ssize' => '19.50 MM', 'is_active' => 'Yes'],
            ['id' => 60, 'pcode_id' => 16, 'schar' => 'U', 'item_name' => 'FINGERRING', 'ssize' => '19.90 MM', 'is_active' => 'Yes'],
            ['id' => 61, 'pcode_id' => 16, 'schar' => 'X', 'item_name' => 'FINGERRING', 'ssize' => '21.10 MM', 'is_active' => 'Yes'],
            ['id' => 62, 'pcode_id' => 16, 'schar' => 'Y', 'item_name' => 'FINGERRING', 'ssize' => '21.50 MM', 'is_active' => 'Yes'],
            ['id' => 63, 'pcode_id' => 16, 'schar' => 'Z', 'item_name' => 'FINGERRING', 'ssize' => '21.90 MM', 'is_active' => 'Yes'],
            ['id' => 64, 'pcode_id' => 26, 'schar' => 'F', 'item_name' => 'OVAL BANGLE', 'ssize' => '53*60 MM', 'is_active' => 'Yes'],
            ['id' => 65, 'pcode_id' => 26, 'schar' => 'G', 'item_name' => 'OVAL BANGLE', 'ssize' => '50*59 MM', 'is_active' => 'Yes'],
            ['id' => 66, 'pcode_id' => 26, 'schar' => 'W', 'item_name' => 'ROUND BANGLE', 'ssize' => '72.50 MM', 'is_active' => 'Yes'],
            ['id' => 67, 'pcode_id' => 29, 'schar' => 'A', 'item_name' => 'MANGALSUTRA', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 68, 'pcode_id' => 29, 'schar' => 'F', 'item_name' => 'MANGALSUTRA', 'ssize' => '17 INCHES', 'is_active' => 'Yes'],
            ['id' => 69, 'pcode_id' => 29, 'schar' => 'G', 'item_name' => 'MANGALSUTRA', 'ssize' => '18 INCHES', 'is_active' => 'Yes'],
            ['id' => 70, 'pcode_id' => 29, 'schar' => 'H', 'item_name' => 'MANGALSUTRA', 'ssize' => '19 INCHES', 'is_active' => 'Yes'],
            ['id' => 71, 'pcode_id' => 29, 'schar' => 'I', 'item_name' => 'MANGALSUTRA', 'ssize' => '20 INCHES', 'is_active' => 'Yes'],
            ['id' => 72, 'pcode_id' => 29, 'schar' => 'J', 'item_name' => 'MANGALSUTRA', 'ssize' => '21 INCHES', 'is_active' => 'Yes'],
            ['id' => 73, 'pcode_id' => 29, 'schar' => 'K', 'item_name' => 'MANGALSUTRA', 'ssize' => '22 INCHES', 'is_active' => 'Yes'],
            ['id' => 74, 'pcode_id' => 29, 'schar' => 'L', 'item_name' => 'MANGALSUTRA', 'ssize' => '23 INCHES', 'is_active' => 'Yes'],
            ['id' => 75, 'pcode_id' => 29, 'schar' => 'M', 'item_name' => 'MANGALSUTRA', 'ssize' => '24 INCHES', 'is_active' => 'Yes'],
            ['id' => 76, 'pcode_id' => 29, 'schar' => 'N', 'item_name' => 'MANGALSUTRA', 'ssize' => '25 INCHES', 'is_active' => 'Yes'],
            ['id' => 77, 'pcode_id' => 29, 'schar' => 'O', 'item_name' => 'MANGALSUTRA', 'ssize' => '26 INCHES', 'is_active' => 'Yes'],
            ['id' => 78, 'pcode_id' => 29, 'schar' => 'P', 'item_name' => 'MANGALSUTRA', 'ssize' => '27 INCHES', 'is_active' => 'Yes'],
            ['id' => 79, 'pcode_id' => 29, 'schar' => 'Q', 'item_name' => 'MANGALSUTRA', 'ssize' => '28 INCHES', 'is_active' => 'Yes'],
            ['id' => 80, 'pcode_id' => 29, 'schar' => 'R', 'item_name' => 'MANGALSUTRA', 'ssize' => '29 INCHES', 'is_active' => 'Yes'],
            ['id' => 81, 'pcode_id' => 29, 'schar' => 'S', 'item_name' => 'MANGALSUTRA', 'ssize' => '30 INCHES', 'is_active' => 'Yes'],
            ['id' => 82, 'pcode_id' => 29, 'schar' => 'T', 'item_name' => 'MANGALSUTRA', 'ssize' => '31 INCHES', 'is_active' => 'Yes'],
            ['id' => 83, 'pcode_id' => 29, 'schar' => 'U', 'item_name' => 'MANGALSUTRA', 'ssize' => '32 INCHES', 'is_active' => 'Yes'],
            ['id' => 84, 'pcode_id' => 14, 'schar' => 'A', 'item_name' => 'DROP EARRING', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 85, 'pcode_id' => 18, 'schar' => 'A', 'item_name' => 'HOOP EAR RING', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 86, 'pcode_id' => 19, 'schar' => 'A', 'item_name' => 'JHUMAKA', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 87, 'pcode_id' => 11, 'schar' => 'A', 'item_name' => 'ARMLATE', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 88, 'pcode_id' => 15, 'schar' => 'A', 'item_name' => 'HARAM', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 89, 'pcode_id' => 24, 'schar' => 'A', 'item_name' => 'PENDENT', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 90, 'pcode_id' => 17, 'schar' => 'A', 'item_name' => 'PENDENT_CHAIN', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 91, 'pcode_id' => 20, 'schar' => 'A', 'item_name' => 'TIKKA', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 92, 'pcode_id' => 21, 'schar' => 'A', 'item_name' => 'ANKLET', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 93, 'pcode_id' => 22, 'schar' => 'A', 'item_name' => 'NECKLACE', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 94, 'pcode_id' => 23, 'schar' => 'A', 'item_name' => 'NOTH', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 95, 'pcode_id' => 25, 'schar' => 'A', 'item_name' => 'STUD EARRING', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 96, 'pcode_id' => 28, 'schar' => 'A', 'item_name' => 'OTHERS', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 97, 'pcode_id' => 30, 'schar' => 'A', 'item_name' => 'COIN', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 98, 'pcode_id' => 15, 'schar' => '1', 'item_name' => 'With Tassel', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 99, 'pcode_id' => 3, 'schar' => '1', 'item_name' => 'With Tassel', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 100, 'pcode_id' => 22, 'schar' => '1', 'item_name' => 'With Tassel', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 101, 'pcode_id' => 15, 'schar' => 'A', 'item_name' => 'With Backchain', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 102, 'pcode_id' => 3, 'schar' => 'A', 'item_name' => 'With Backchain', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 103, 'pcode_id' => 22, 'schar' => 'A', 'item_name' => 'With Backchain', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 104, 'pcode_id' => 4, 'schar' => '1', 'item_name' => 'With Tassel', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 105, 'pcode_id' => 5, 'schar' => '1', 'item_name' => 'With Tassel', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 106, 'pcode_id' => 6, 'schar' => '1', 'item_name' => 'With Tassel', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 107, 'pcode_id' => 7, 'schar' => '1', 'item_name' => 'With Tassel', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 108, 'pcode_id' => 8, 'schar' => '1', 'item_name' => 'With Tassel', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 109, 'pcode_id' => 9, 'schar' => '1', 'item_name' => 'With Tassel', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 110, 'pcode_id' => 10, 'schar' => '1', 'item_name' => 'With Tassel', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 111, 'pcode_id' => 4, 'schar' => 'A', 'item_name' => 'With Backchain', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 112, 'pcode_id' => 5, 'schar' => 'A', 'item_name' => 'With Backchain', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 113, 'pcode_id' => 6, 'schar' => 'A', 'item_name' => 'With Backchain', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 114, 'pcode_id' => 7, 'schar' => 'A', 'item_name' => 'With Backchain', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 115, 'pcode_id' => 8, 'schar' => 'A', 'item_name' => 'With Backchain', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 116, 'pcode_id' => 9, 'schar' => 'A', 'item_name' => 'With Backchain', 'ssize' => 'NA', 'is_active' => 'Yes'],
            ['id' => 117, 'pcode_id' => 10, 'schar' => 'A', 'item_name' => 'With Backchain', 'ssize' => 'NA', 'is_active' => 'Yes']
        ]);
    }
}
