<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VoucherTypesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('vouchertypes')->insert([
            [
                'id' => 8,
                'location_id' => 3,
                'voucher_type' => 'gold_receipt_entry',
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-08-01',
                'startno' => '001',
                'prefix' => 'PHO',
                'suffix' => 'GRE/25-26',
                'status' => 'Active',
                'lastno' => '2',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-07-31 03:31:29',
                'updated_at' => '2025-08-31 23:39:31',
            ],
            [
                'id' => 9,
                'location_id' => 3,
                'voucher_type' => 'gold_issue_entry',
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-08-01',
                'startno' => '001',
                'prefix' => 'PHO',
                'suffix' => 'GI/25-26',
                'status' => 'Active',
                'lastno' => '001',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-07-31 03:34:44',
                'updated_at' => '2025-07-31 03:34:44',
            ],
            [
                'id' => 10,
                'location_id' => 3,
                'voucher_type' => 'quality_check',
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-08-01',
                'startno' => '001',
                'prefix' => 'PJ',
                'suffix' => 'QC',
                'status' => 'Active',
                'lastno' => '4',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-09-01 10:07:34',
                'updated_at' => '2025-09-11 23:03:11',
            ],
            [
                'id' => 11,
                'location_id' => 3,
                'voucher_type' => 'finished_goods_entry',
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-08-01',
                'startno' => '001',
                'prefix' => 'PJ',
                'suffix' => 'FGE',
                'status' => 'Active',
                'lastno' => '001',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-09-01 10:08:07',
                'updated_at' => '2025-09-01 10:08:07',
            ],
            [
                'id' => 12,
                'location_id' => 3,
                'voucher_type' => 'return_gold_from_karigar',
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-08-01',
                'startno' => '001',
                'prefix' => 'PJ',
                'suffix' => 'RGK',
                'status' => 'Active',
                'lastno' => '001',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-09-01 10:08:40',
                'updated_at' => '2025-09-01 10:08:40',
            ],
            [
                'id' => 13,
                'location_id' => 4,
                'voucher_type' => 'gold_receipt_entry',
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-09-01',
                'startno' => '001',
                'prefix' => 'PJT',
                'suffix' => 'GR',
                'status' => 'Active',
                'lastno' => '002',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-09-05 02:26:24',
                'updated_at' => '2025-09-05 02:27:58',
            ],
            [
                'id' => 14,
                'location_id' => 4,
                'voucher_type' => 'gold_issue_entry',
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-09-01',
                'startno' => '00001',
                'prefix' => 'PJT',
                'suffix' => 'GI',
                'status' => 'Active',
                'lastno' => '002',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-09-05 02:30:20',
                'updated_at' => '2025-09-05 02:32:00',
            ],
            [
                'id' => 15,
                'location_id' => 4,
                'voucher_type' => 'quality_check',
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-09-01',
                'startno' => '0001',
                'prefix' => 'PJT',
                'suffix' => 'QC',
                'status' => 'Active',
                'lastno' => '6',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-09-05 02:33:28',
                'updated_at' => '2025-09-12 01:16:10',
            ],
            [
                'id' => 16,
                'location_id' => 4,
                'voucher_type' => 'finished_goods_entry',
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-09-01',
                'startno' => '00001',
                'prefix' => 'PJT',
                'suffix' => 'FG',
                'status' => 'Active',
                'lastno' => '002',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-09-05 02:37:15',
                'updated_at' => '2025-09-05 02:46:30',
            ],
        ]);
    }
}
