<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VoucherTypesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('vouchertypes')->insert([
            [
                'id' => 8,
                'location_id' => 3,
                'voucher_type' => 'gold_receipt_entry',
                'financial_year_id' => 3,
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-08-01',
                'startno' => '001',
                'prefix' => 'PHO',
                'suffix' => 'GRE/25-26',
                'status' => 'Active',
                'lastno' => '1',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-07-30 22:01:29',
                'updated_at' => '2025-08-31 18:09:31',
            ],
            [
                'id' => 9,
                'location_id' => 3,
                'voucher_type' => 'gold_issue_entry',
                'financial_year_id' => 3,
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-08-01',
                'startno' => '001',
                'prefix' => 'PHO',
                'suffix' => 'GI/25-26',
                'status' => 'Active',
                'lastno' => '1',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-07-30 22:04:44',
                'updated_at' => '2025-07-30 22:04:44',
            ],
            [
                'id' => 10,
                'location_id' => 3,
                'voucher_type' => 'quality_check',
                'financial_year_id' => 3,
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-08-01',
                'startno' => '001',
                'prefix' => 'PJ',
                'suffix' => 'QC',
                'status' => 'Active',
                'lastno' => '1',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-09-01 04:37:34',
                'updated_at' => '2025-09-11 17:33:11',
            ],
            [
                'id' => 11,
                'location_id' => 3,
                'voucher_type' => 'finished_goods_entry',
                'financial_year_id' => 3,
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-08-01',
                'startno' => '001',
                'prefix' => 'PJ',
                'suffix' => 'FGE',
                'status' => 'Active',
                'lastno' => '1',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-09-01 04:38:07',
                'updated_at' => '2025-09-01 04:38:07',
            ],
            [
                'id' => 12,
                'location_id' => 3,
                'voucher_type' => 'return_gold_from_karigar',
                'financial_year_id' => 3,
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-08-01',
                'startno' => '001',
                'prefix' => 'PJ',
                'suffix' => 'RGK',
                'status' => 'Active',
                'lastno' => '1',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-09-01 04:38:40',
                'updated_at' => '2025-09-01 04:38:40',
            ],
            [
                'id' => 13,
                'location_id' => 4,
                'voucher_type' => 'gold_receipt_entry',
                'financial_year_id' => 3,
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-09-01',
                'startno' => '001',
                'prefix' => 'PJT',
                'suffix' => 'GR',
                'status' => 'Active',
                'lastno' => '1',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-09-04 20:56:24',
                'updated_at' => '2025-09-04 20:57:58',
            ],
            [
                'id' => 14,
                'location_id' => 4,
                'voucher_type' => 'gold_issue_entry',
                'financial_year_id' => 3,
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-09-01',
                'startno' => '00001',
                'prefix' => 'PJT',
                'suffix' => 'GI',
                'status' => 'Active',
                'lastno' => '1',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-09-04 21:00:20',
                'updated_at' => '2025-09-04 21:02:00',
            ],
            [
                'id' => 15,
                'location_id' => 4,
                'voucher_type' => 'quality_check',
                'financial_year_id' => 3,
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-09-01',
                'startno' => '0001',
                'prefix' => 'PJT',
                'suffix' => 'QC',
                'status' => 'Active',
                'lastno' => '1',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-09-04 21:03:28',
                'updated_at' => '2025-09-11 19:46:10',
            ],
            [
                'id' => 16,
                'location_id' => 4,
                'voucher_type' => 'finished_goods_entry',
                'financial_year_id' => 3,
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-09-01',
                'startno' => '00001',
                'prefix' => 'PJT',
                'suffix' => 'FG',
                'status' => 'Active',
                'lastno' => '1',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-09-04 21:07:15',
                'updated_at' => '2025-09-04 21:16:30',
            ],
            [
                'id' => 17,
                'location_id' => 3,
                'voucher_type' => 'stock_transfer',
                'financial_year_id' => 3,
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-10-01',
                'startno' => '001',
                'prefix' => 'PJST',
                'suffix' => 'HO',
                'status' => 'Active',
                'lastno' => '1',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-10-14 09:52:48',
                'updated_at' => '2025-10-14 09:52:48',
            ],
            [
                'id' => 18,
                'location_id' => 4,
                'voucher_type' => 'stock_transfer',
                'financial_year_id' => 3,
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-10-01',
                'startno' => '001',
                'prefix' => 'PJST',
                'suffix' => 'HO-T',
                'status' => 'Active',
                'lastno' => '1',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-10-14 09:53:23',
                'updated_at' => '2025-10-14 09:53:23',
            ],
            [
                'id' => 19,
                'location_id' => 3,
                'voucher_type' => 'finished_product_pdi_list',
                'financial_year_id' => 3,
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-10-01',
                'startno' => '0001',
                'prefix' => 'PJHO',
                'suffix' => 'PDI',
                'status' => 'Active',
                'lastno' => '1',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-10-14 09:53:23',
                'updated_at' => '2025-10-14 09:53:23',
            ],
            [
                'id' => 20,
                'location_id' => 4,
                'voucher_type' => 'finished_product_pdi_list',
                'financial_year_id' => 3,
                'applicable_year' => '2025-26',
                'applicable_date' => '2025-10-01',
                'startno' => '0001',
                'prefix' => 'PJHT',
                'suffix' => 'PDI',
                'status' => 'Active',
                'lastno' => '1',
                'created_by' => 'Super Admin',
                'updated_by' => null,
                'created_at' => '2025-10-14 09:53:23',
                'updated_at' => '2025-10-14 09:53:23',
            ]
        ]);
    }
}